CREATE ROLE [PreCheck_DEVs]
    AUTHORIZATION [dbo];


GO
ALTER ROLE [PreCheck_DEVs] ADD MEMBER [PRECHECK\SQL_Devs];


GO
ALTER ROLE [PreCheck_DEVs] ADD MEMBER [SQLDevCarcoUser];


GO
ALTER ROLE [PreCheck_DEVs] ADD MEMBER [SQLLoginCarco_BI];


GO
ALTER ROLE [PreCheck_DEVs] ADD MEMBER [CARCOGROUP.COM\DDegenaro];


GO
ALTER ROLE [PreCheck_DEVs] ADD MEMBER [CarcoGroup.com\SQL_Devs];


GO
ALTER ROLE [PreCheck_DEVs] ADD MEMBER [CARCOGROUP.COM\CDeCook];


GO
ALTER ROLE [PreCheck_DEVs] ADD MEMBER [CARCOGROUP.COM\i61866];


GO
ALTER ROLE [PreCheck_DEVs] ADD MEMBER [CARCOGROUP.COM\i51339];


GO
ALTER ROLE [PreCheck_DEVs] ADD MEMBER [CARCOGROUP.COM\HIRPatel];

