CREATE PARTITION SCHEME [PS1_ProfLic]
    AS PARTITION [PF1_ProfLic]
    TO ([FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA]);

