CREATE PARTITION SCHEME [PS1_MedInteg]
    AS PARTITION [PF1_MedInteg]
    TO ([FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA]);

