CREATE PARTITION SCHEME [PS1_APPL]
    AS PARTITION [PF1_APNO]
    TO ([FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA]);

