CREATE PARTITION SCHEME [PS1_Civil]
    AS PARTITION [PF1_Civil]
    TO ([FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA]);

