CREATE PARTITION SCHEME [PS1_Credit]
    AS PARTITION [PF1_Credit]
    TO ([FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA], [FG_DATA]);

