CREATE TABLE [REPORT].[ordersummary_20220125] (
    [OrderNumber]          INT           NOT NULL,
    [Applicant_FirstName]  VARCHAR (50)  NULL,
    [Applicant_LastName]   VARCHAR (50)  NULL,
    [Applicant_MiddleName] VARCHAR (50)  NULL,
    [Applicant_UID]        VARCHAR (12)  NULL,
    [OrderCreateDate]      DATETIME      NOT NULL,
    [ClientId]             INT           NOT NULL,
    [ProgramId]            INT           NULL,
    [ProgramName]          VARCHAR (250) NULL,
    [ApDate]               DATETIME      NULL,
    [HasBackground]        BIT           NOT NULL,
    [HasDrugScreen]        BIT           NOT NULL,
    [HasImmunization]      BIT           NOT NULL,
    [BG_OrderStatusId]     SMALLINT      NULL,
    [BG_OrderStatus]       VARCHAR (1)   NULL,
    [BG_CompleteDate]      DATETIME      NULL,
    [BG_ResultId]          SMALLINT      NULL,
    [BG_Result]            VARCHAR (20)  NULL,
    [DT_OrderStatusId]     SMALLINT      NULL,
    [DT_OrderStatus]       VARCHAR (1)   NULL,
    [DT_CompleteDate]      DATETIME      NULL,
    [DT_ResultId]          SMALLINT      NULL,
    [DT_Result]            VARCHAR (20)  NULL,
    [DT_OrderId]           INT           NULL,
    [DT_ReportId]          INT           NULL,
    [IM_OrderStatusId]     SMALLINT      NULL,
    [IM_OrderStatus]       VARCHAR (1)   NULL,
    [IM_ResultId]          SMALLINT      NULL,
    [IM_Result]            VARCHAR (20)  NULL,
    [OrderStatusId]        SMALLINT      NULL,
    [CreateDate]           DATETIME      NOT NULL,
    [ModifyDate]           DATETIME      NOT NULL
);

