Create view [STG].[Persref_CT]
as
SELECT  Null [PersRefID]
      ,ApplicantNumber [APNO]
      ,Null [SectStat]
      ,Null [Worksheet]
      ,[ReferenceName] [Name]
      ,[Phone] [Phone]
      ,Null [Rel_V]
      ,Null [Years_V]
      ,Null [Priv_Notes]
      ,Null [Pub_Notes]
      ,[ModifyDate] [Last_Updated]
      ,Null [Investigator]
      ,Null [Emplid]
      ,Null [PendingUpdated]
      ,Null [Web_Status]
      ,Null [web_updated]
      ,Null [time_in]
      ,Null [InUse]
      ,[CreateDate] [CreatedDate]
      ,Null [Last_Worked]
      ,Null [IsCAMReview]
      ,Null [IsOnReport]
      ,Null [IsHidden]
      ,Null [IsHistoryRecord]
      ,Null [ClientAdjudicationStatus]
      ,[Email] [Email]
      ,[JobTitle] [JobTitle]
      ,Null [InUse_TimeStamp]
	,Operation
 FROM [STG].[ApplicantReference_CT]

