



CREATE view [STG].[ProfLic_CT]
as
SELECT Null [ProfLicID]
      ,ApplicantNumber [Apno]
      ,Null [SectStat]
      ,Null [Worksheet]
      ,LicenseType [Lic_Type]
      ,LicenseNumber [Lic_No]
      ,IssueDate [Year]
      ,ExpirationDate [Expire]
      ,State [State]
      ,Null [Status]
      ,Null [Priv_Notes]
      ,Null [Pub_Notes]
      ,Null [Web_status]
      ,Null [includealias]
      ,Null [includealias2]
      ,Null [includealias3]
      ,Null [includealias4]
      ,Null [pendingupdated]
      ,Null [web_updated]
      ,Null [time_in]
      ,Null [Organization]
      ,Null [Contact_Name]
      ,Null [Contact_Title]
      ,Null [Contact_Date]
      ,Null [Investigator]
      ,ModifyDate [Last_Updated]
      ,Null [InUse]
      ,CreateDate [CreatedDate]
      ,Null [Status_A]
      ,Null [ToPending]
      ,Null [FromPending]
      ,Null [Last_Worked]
      ,Null [IsCAMReview]
      ,Null [IsOnReport]
      ,Null [IsHidden]
      ,Null [IsHistoryRecord]
      ,Null [ClientAdjudicationStatus]
      ,Null [ClientRefID]
      ,Null [Lic_Type_V]
      ,Null [Lic_No_V]
      ,Null [State_V]
      ,Null [Expire_V]
      ,Null [Year_V]
      ,Null [GenerateCertificate]
      ,Null [CertificateAvailabilityStatus]
      ,Null [DisclosedPastAction]
      ,Null [InUse_TimeStamp]
      ,Null [NameOnLicense_V]
      ,Null [Speciality_V]
      ,[IsValidLifeTime]
      ,Null [MultiState_V]
      ,Null [BoardActions_V]
      ,Null [ContactMethod_V]
      ,Null [LicenseTypeID]
	  ,Operation
FROM [STG].[ApplicantLicense_CT]




