/*
Procedure Name : [dbo].[ReportEmplByApDate_Pct]
Requested By: Milton Robins
Developer: Deepak Vodethela
Execution : EXEC [dbo].[ReportEmplByApDate_Pct] '10/01/2016','10/21/2016','JMonfort'
			EXEC [dbo].[ReportEmplByApDate_Pct] '10/01/2016','10/21/2016',NULL
*/

CREATE PROCEDURE [dbo].[ReportEmplByApDate_Pct]
	@StartDate DateTime,
	@EndDate DateTime,
	@Investigator VARCHAR(MAX) = NULL
AS
BEGIN

-- Assign the Investigator to NULL
IF LEN(@Investigator) = 0 
	BEGIN 
		SET @Investigator = NULL 
	END

	SELECT E1.INVESTIGATOR,
		( SELECT COUNT( * )
			FROM APPL A (NOLOCK) INNER JOIN EMPL E2 (NOLOCK) ON A.APNO = E2.APNO
			WHERE E2.IsOnReport = 1 AND A.APDATE >= @STARTDATE AND A.APDATE < @ENDDATE AND E2.INVESTIGATOR = E1.INVESTIGATOR AND E2.SectStat IN ('5','6','7','8') AND A.APDATE IS NOT NULL AND E2.Last_Updated IS NOT NULL) AS TOTAL,
	
			CAST( 100 * ( SELECT COUNT( * )
			FROM APPL A (NOLOCK) INNER JOIN EMPL E2 (NOLOCK) ON A.APNO = E2.APNO
			WHERE E2.IsOnReport = 1 AND A.APDATE >= @STARTDATE AND A.APDATE < @ENDDATE AND E2.INVESTIGATOR = E1.INVESTIGATOR AND E2.SectStat IN ('5','6','7','8') AND A.APDATE IS NOT NULL AND E2.Last_Updated IS NOT NULL AND DBO.ELAPSEDBUSINESSDAYS_2(A.APDATE, E2.Last_Updated ) = 0 ) /
			( SELECT CASE WHEN COUNT( * ) = 0 THEN 1 ELSE COUNT( * ) END --> Used case statement to avoid Divide By zero error. 
			FROM APPL A (NOLOCK) INNER JOIN EMPL E2 (NOLOCK) ON A.APNO = E2.APNO
			WHERE  E2.IsOnReport = 1 AND A.APDATE >= @STARTDATE AND A.APDATE < @ENDDATE AND E2.INVESTIGATOR = E1.INVESTIGATOR AND E2.SectStat IN ('5','6','7','8') AND A.APDATE IS NOT NULL AND E2.Last_Updated IS NOT NULL ) AS DECIMAL(5, 2 ) ) AS 'SameDay',

			CAST( 100 * ( SELECT COUNT( * )
			FROM APPL A (NOLOCK) INNER JOIN EMPL E2 (NOLOCK) ON A.APNO = E2.APNO
			WHERE E2.IsOnReport = 1 AND A.APDATE >= @STARTDATE AND A.APDATE < @ENDDATE AND E2.INVESTIGATOR = E1.INVESTIGATOR AND E2.SectStat IN ('5','6','7','8') AND A.APDATE IS NOT NULL AND E2.Last_Updated IS NOT NULL AND DBO.ELAPSEDBUSINESSDAYS_2(A.APDATE, E2.Last_Updated ) = 1 ) /
			( SELECT CASE WHEN COUNT( * ) = 0 THEN 1 ELSE COUNT( * ) END
			FROM APPL A (NOLOCK) INNER JOIN EMPL E2 (NOLOCK) ON A.APNO = E2.APNO
			WHERE  E2.IsOnReport = 1 AND A.APDATE >= @STARTDATE AND A.APDATE< @ENDDATE AND E2.INVESTIGATOR = E1.INVESTIGATOR AND E2.SectStat IN ('5','6','7','8') AND A.APDATE IS NOT NULL AND E2.Last_Updated IS NOT NULL ) AS DECIMAL( 5, 2 ) ) AS 'OneDay',

			CAST( 100 * ( SELECT COUNT( * )
			FROM APPL A (NOLOCK) INNER JOIN EMPL E2 (NOLOCK) ON A.APNO = E2.APNO
			WHERE E2.IsOnReport = 1 AND A.APDATE >= @STARTDATE AND A.APDATE < @ENDDATE AND E2.INVESTIGATOR = E1.INVESTIGATOR AND E2.SectStat IN ('5','6','7','8') AND A.APDATE IS NOT NULL AND E2.Last_Updated IS NOT NULL AND DBO.ELAPSEDBUSINESSDAYS_2(A.APDATE, E2.Last_Updated ) = 2 ) /
			( SELECT CASE WHEN COUNT( * ) = 0 THEN 1 ELSE COUNT( * ) END
			FROM APPL A (NOLOCK) INNER JOIN EMPL E2 (NOLOCK) ON A.APNO = E2.APNO
			WHERE  E2.IsOnReport = 1 AND A.APDATE >= @STARTDATE AND A.APDATE < @ENDDATE AND E2.INVESTIGATOR = E1.INVESTIGATOR AND E2.SectStat IN ('5','6','7','8') AND A.APDATE IS NOT NULL AND E2.Last_Updated IS NOT NULL ) AS DECIMAL( 5, 2 ) ) AS 'TwoDays',

			CAST( 100 * ( SELECT COUNT( * )
			FROM APPL A (NOLOCK) INNER JOIN EMPL E2 (NOLOCK) ON A.APNO = E2.APNO
			WHERE E2.IsOnReport = 1 AND A.APDATE >= @STARTDATE AND A.APDATE< @ENDDATE AND E2.INVESTIGATOR = E1.INVESTIGATOR AND E2.SectStat IN ('5','6','7','8') AND A.APDATE IS NOT NULL AND E2.Last_Updated IS NOT NULL AND DBO.ELAPSEDBUSINESSDAYS_2(A.APDATE, E2.Last_Updated ) = 3 ) /
			( SELECT CASE WHEN COUNT( * ) = 0 THEN 1 ELSE COUNT( * ) END
			FROM APPL A (NOLOCK) INNER JOIN EMPL E2 (NOLOCK) ON A.APNO = E2.APNO
			WHERE  E2.IsOnReport = 1 AND A.APDATE >= @STARTDATE AND A.APDATE < @ENDDATE AND E2.INVESTIGATOR = E1.INVESTIGATOR AND E2.SectStat IN ('5','6','7','8') AND A.APDATE IS NOT NULL AND E2.Last_Updated IS NOT NULL) AS DECIMAL( 5, 2 ) ) AS 'ThreeDays',

			CAST( 100 * ( SELECT COUNT( * )
			FROM APPL A (NOLOCK) INNER JOIN EMPL E2 (NOLOCK) ON A.APNO = E2.APNO
			WHERE  E2.IsOnReport = 1 AND A.APDATE >= @STARTDATE AND A.APDATE < @ENDDATE AND E2.INVESTIGATOR = E1.INVESTIGATOR AND E2.SectStat IN ('5','6','7','8') AND A.APDATE IS NOT NULL AND E2.Last_Updated IS NOT NULL AND DBO.ELAPSEDBUSINESSDAYS_2(A.APDATE, E2.Last_Updated ) = 4 ) /
			( SELECT CASE WHEN COUNT( * ) = 0 THEN 1 ELSE COUNT( * ) END
			FROM APPL A (NOLOCK) INNER JOIN EMPL E2 (NOLOCK) ON A.APNO = E2.APNO
			WHERE E2.IsOnReport = 1 AND A.APDATE >= @STARTDATE AND A.APDATE < @ENDDATE AND E2.INVESTIGATOR = E1.INVESTIGATOR AND E2.SectStat IN ('5','6','7','8') AND A.APDATE IS NOT NULL AND E2.Last_Updated IS NOT NULL) AS DECIMAL( 5, 2 ) ) AS 'FourDays',

			CAST( 100 * ( SELECT COUNT( * )
			FROM APPL A (NOLOCK) INNER JOIN EMPL E2 (NOLOCK) ON A.APNO = E2.APNO
			WHERE E2.IsOnReport = 1 AND A.APDATE >= @STARTDATE AND A.APDATE < @ENDDATE AND E2.INVESTIGATOR = E1.INVESTIGATOR AND E2.SectStat IN ('5','6','7','8') AND A.APDATE IS NOT NULL AND E2.Last_Updated IS NOT NULL AND DBO.ELAPSEDBUSINESSDAYS_2(A.APDATE, E2.Last_Updated) = 5  ) /
			( SELECT CASE WHEN COUNT( * ) = 0 THEN 1 ELSE COUNT( * ) END
			FROM APPL A (NOLOCK) INNER JOIN EMPL E2 (NOLOCK) ON A.APNO = E2.APNO
			WHERE E2.IsOnReport = 1 AND A.APDATE >= @STARTDATE AND A.APDATE< @ENDDATE AND E2.INVESTIGATOR = E1.INVESTIGATOR AND E2.SectStat IN ('5','6','7','8') AND A.APDATE IS NOT NULL AND E2.Last_Updated IS NOT NULL ) AS DECIMAL( 5, 2 ) ) AS 'FiveDays',
		
			CAST( 100 * ( SELECT COUNT( * )
			FROM APPL A (NOLOCK) INNER JOIN EMPL E2 (NOLOCK) ON A.APNO = E2.APNO
			WHERE E2.IsOnReport = 1 AND  A.APDATE >= @STARTDATE AND A.APDATE < @ENDDATE AND E2.INVESTIGATOR = E1.INVESTIGATOR AND E2.SectStat IN ('5','6','7','8') AND A.APDATE IS NOT NULL AND E2.Last_Updated IS NOT NULL AND DBO.ELAPSEDBUSINESSDAYS_2(A.APDATE, E2.Last_Updated ) = 6  ) /
			( SELECT CASE WHEN COUNT( * ) = 0 THEN 1 ELSE COUNT( * ) END
			FROM APPL A (NOLOCK) INNER JOIN EMPL E2 (NOLOCK) ON A.APNO = E2.APNO
			WHERE E2.IsOnReport = 1 AND A.APDATE >= @STARTDATE AND A.APDATE < @ENDDATE AND E2.INVESTIGATOR = E1.INVESTIGATOR AND E2.SectStat IN ('5','6','7','8') AND A.APDATE IS NOT NULL AND E2.Last_Updated IS NOT NULL ) AS DECIMAL( 5, 2 ) ) AS 'SixDays',

			'100' As  '> SixDays'
	FROM APPL A (NOLOCK) INNER JOIN EMPL E1 (NOLOCK) ON A.APNO = E1.APNO
	WHERE E1.IsOnReport = 1 AND  A.APDATE >= @STARTDATE AND  A.APDATE < @ENDDATE AND (E1.INVESTIGATOR IS NOT NULL AND E1.INVESTIGATOR <> '0') AND A.APDATE IS NOT NULL AND E1.Last_Updated IS NOT NULL AND (@Investigator IS NULL OR E1.Investigator LIKE '%' + @Investigator + '%')
	GROUP BY E1.INVESTIGATOR
	ORDER BY E1.INVESTIGATOR

END