-- =============================================
-- Author:		Radhika Dereddy
-- Create date: 01/27/2017
-- Description:	Tenet Submission Report with package
-- Modified :  Radhika Dereddy 09/20/2017
-- Decription : Total Additional Cost and Total
-- EXEC [Tenet_Submission_Report_w_Pkg] '09/01/2018', '09/30/2018', 'Tenet'
-- Modified by Radhika Dereddy on 10/09/2018 
-- Modified to get the correct Package Price from the CLient package table
-- =============================================
CREATE PROCEDURE [dbo].[Tenet_Submission_Report_w_Pkg]
	-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE
	@STARTDATE DATETIME,
	@ENDDATE DATETIME,
	@AFFILIATE VARCHAR(MAX) = NULL
AS
BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
	SET NOCOUNT ON;

    -- INSERT STATEMENTS FOR PROCEDURE HERE
SELECT C.CLNO AS 'CLIENT ID', C.NAME AS 'CLIENT NAME', C.CONTACT AS 'CONTACT NAME', C.CAM, A.FIRST AS 'FIRST NAME', 
A.LAST AS 'LAST NAME', A.APNO AS 'REPORT NUMBER', A.ENTEREDVIA AS 'SUBMITTED VIA', PM.PACKAGEDESC AS 'PACKAGE ORDERED', ISNULL(CP.RATE, PM.DEFAULTPRICE)'Package', 
ISNULL((SELECT SUM(I.AMOUNT) FROM INVDETAIL I (NOLOCK)  WHERE I.APNO =A.APNO AND  I.TYPE > 0 ),0.00) AS 'TOTAL ADDITIONAL COST', 
ISNULL((SELECT SUM(I.AMOUNT) FROM INVDETAIL I (NOLOCK)  WHERE I.APNO =A.APNO AND  I.TYPE > 0 ),0.00) + ISNULL(PM.DEFAULTPRICE,0.00)  AS 'TOTAL REPORT COST',
DBO.ELAPSEDBUSINESSDAYS_2( A.APDATE, A.ORIGCOMPDATE ) AS 'TURNAROUND TIME IN DAYS',
A.APDATE AS 'SUBMISSION TIME', A.ORIGCOMPDATE AS 'COMPLETE DATE', RF.AFFILIATE AS 'AFFILIATE', RF.AFFILIATEID AS 'AFFILIATEID'
FROM CLIENT C
INNER JOIN APPL A ON A.CLNO = C.CLNO
INNER jOIN ClientPackages Cp on c.CLNO = cp.CLNO and A.PackageID = Cp.Packageid
INNER JOIN PACKAGEMAIN PM ON A.PACKAGEID = PM.PACKAGEID
INNER JOIN REFAFFILIATE RF ON RF.AFFILIATEID = C.AFFILIATEID
WHERE (A.APDATE >= @STARTDATE AND A.APDATE <= @ENDDATE) 
AND ( RF.AFFILIATE LIKE '%' + @AFFILIATE +'%')
ORDER BY C.CLNO


--HAhmed 9/25/2018 HDT #40266 Fix to resolve not adding correctly the Package Cost and the Total Additional Cost.
--(SELECT SUM(ID.AMOUNT) FROM INVDETAIL ID (NOLOCK)  WHERE ID.APNO = A.APNO) AS 'TOTAL REPORT COST',
END
