-- =============================================
-- Author:		Radhika Dereddy
-- Create date: 04/11/2017
-- Description:	Brian: This is for tracking and client reporting purposes (especially Tenet).  
-- We need to know the Adjudication Status of each report.
-- Modified Date: RD- 04/12/2017 Added a new column IsHidden and added a parameter CLNO .
-- EXEC Adjudication_Status_Report '10/01/2017','10/31/2017',0, 10
-- Modified by Amy liu on 09/09/2020 for phase3 of project: IntranetModule: Status-SubStatus
/* Modified By: Vairavan A
-- Modified Date: 07/01/2022
-- Description: Ticketno-53763 
Modify existing q-reports that have affiliate ids in their search parameters
Details: 
Change search parameters for the Affiliate Id field
     * search by multiple affiliate ids (ex 4:297)
     * want to also be able to search all affiliates by putting zero - meaning 0 to search all affiliates
     * multiple affiliates to be separated by a colon  
Under Parameter Names - after Affiliate ID include this wording (separate by colon, default 0)
*/
---Testing
/*
EXEC Adjudication_Status_Report '10/01/2017','10/31/2017',0, '0'
EXEC Adjudication_Status_Report '10/01/2017','10/31/2017',0, '10'
EXEC Adjudication_Status_Report '10/01/2017','10/31/2017',0, '10:2323'
*/
-- =============================================

CREATE PROCEDURE [dbo].[Adjudication_Status_Report]
	-- Add the parameters for the stored procedure here
	@STARTDATE DATETIME,
	@ENDDATE DATETIME,
	@CLNO INT,
--@AffiliateID int,--code commented by vairavan for ticket id -53763
    @AffiliateIDs varchar(MAX) = '0'--code added by vairavan for ticket id -53763

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.

SET NOCOUNT ON;

	--declare @STARTDATE DATETIME = '04/01/2020',
	--		@ENDDATE DATETIME = '07/31/2020',
	--		@CLNO INT = 0,
	--		@AFFILIATEID INT =217

SET @ENDDATE = DATEADD(D,1,@ENDDATE)

--STEP 1 : ADJUDICATION BY COMPONENT - EDUCATION 


	--code added by vairavan for ticket id -53763 starts
	IF @AffiliateIDs = '0' 
	BEGIN  
		SET @AffiliateIDs = NULL  
	END
	--code added by vairavan for ticket id -53763 ends

SELECT C.CLNO, C.NAME, A.APNO, A.LAST, A.FIRST, A.INVESTIGATOR, A.APDATE, A.COMPDATE, 
A.USERID, 'EDUCATION' AS 'COMPONENT TYPE', E.SCHOOL AS 'COMPONENT DATA', SS.DESCRIPTION AS 'COMPONENT STATUS',ISNULL(sss.SectSubStatus,'') as 'COMPONENT SUBSTATUS', CADJ.DESCRIPTION AS 'ADJUDICATIONSTATUS', 
(CASE WHEN ADJ.REVIEWDATE_CAM IS NULL THEN 'FALSE' ELSE 'TRUE' END ) AS 'CAM BOX',
(CASE WHEN ADJ.REVIEWDATE_MGR IS NULL THEN 'FALSE' ELSE 'TRUE' END ) AS 'MGR BOX',
(CASE E.ISHIDDEN WHEN 1 THEN 'UNUSED' ELSE 'ON REPORT' END ) AS ISHIDDEN,
(CASE E.ISONREPORT WHEN 1 THEN 'YES' ELSE 'UNUSED' END ) AS ISONREPORT,
 RF.AFFILIATE
FROM APPL A  with(nolock) 
INNER JOIN CLIENT C  with(nolock) ON C.CLNO = A.CLNO
INNER JOIN EDUCAT E  with(nolock) ON E.APNO = A.APNO 
INNER JOIN APPLADJUDICATIONAUDITTRAIL ADJ  with(nolock) ON ADJ.APNO = A.APNO AND ADJ.SECTIONID = E.EDUCATID
INNER JOIN REFAFFILIATE RF  with(nolock) ON RF.AFFILIATEID = C.AFFILIATEID
INNER JOIN SECTSTAT SS with(nolock)  ON SS.CODE = E.SECTSTAT
INNER JOIN CLIENTADJUDICATIONSTATUS CADJ  with(nolock) ON CADJ.CLIENTADJUDICATIONSTATUSID = E.CLIENTADJUDICATIONSTATUS
left JOIN CLIENTADJUDICATIONSTATUSCUSTOM CADJC with(nolock)  ON CADJC.CLIENTADJUDICATIONSTATUSID = CADJ.CLIENTADJUDICATIONSTATUSID AND CADJ.CLNO = A.CLNO
left join dbo.SectSubStatus sss with(nolock)  on e.SectStat = sss.SectStatusCode and e.SectSubStatusID = sss.SectSubStatusID
WHERE (A.APDATE BETWEEN @STARTDATE AND @ENDDATE)
AND A.CLNO = IIF(@CLNO=0,A.CLNO,@CLNO)
--AND C.AFFILIATEID = IIF(@AFFILIATEID=0, C.AFFILIATEID, @AFFILIATEID)--code commented by vairavan for ticket id -53763
		 and (@AffiliateIDs IS NULL OR c.AffiliateID IN (SELECT value FROM fn_Split(@AffiliateIDs,':')))--code added by vairavan for ticket id -53763
GROUP BY A.APNO, C.CLNO, C.NAME, A.LAST, A.FIRST, A.INVESTIGATOR, A.APDATE, A.COMPDATE, A.USERID,
E.SCHOOL,CADJ.DESCRIPTION, ADJ.REVIEWDATE_CAM,ADJ.REVIEWDATE_MGR, E.ISHIDDEN,E.ISONREPORT, RF.AFFILIATE,SS.DESCRIPTION, ISNULL(sss.SectSubStatus,'')


UNION ALL

--STEP 2 : ADJUDICATION BY COMPONENT - EMPLOYMENT 

SELECT C.CLNO, C.NAME, A.APNO, A.LAST, A.FIRST, A.INVESTIGATOR, A.APDATE, A.COMPDATE,
A.USERID,'EMPLOYMENT' AS 'COMPONENT TYPE', EM.Employer AS 'COMPONENT DATA',SS.DESCRIPTION AS 'COMPONENT STATUS',ISNULL(sss.SectSubStatus,'') AS 'COMPONENT SUBSTATUS',CADJ.DESCRIPTION AS 'ADJUDICATIONSTATUS', 
(CASE WHEN ADJ.REVIEWDATE_CAM IS NULL THEN 'FALSE' ELSE 'TRUE' END ) AS 'CAM BOX',
(CASE WHEN ADJ.REVIEWDATE_MGR IS NULL THEN 'FALSE' ELSE 'TRUE' END ) AS 'MGR BOX',
(CASE EM.ISHIDDEN WHEN 1 THEN 'UNUSED' ELSE 'ON REPORT' END ) AS ISHIDDEN,
(CASE EM.ISONREPORT WHEN 1 THEN 'YES' ELSE 'UNUSED' END ) AS ISONREPORT, RF.AFFILIATE
FROM APPL A with(nolock) 
INNER JOIN CLIENT C  with(nolock) ON C.CLNO = A.CLNO
INNER JOIN EMPL EM  with(nolock) ON EM.APNO = A.APNO 
INNER JOIN APPLADJUDICATIONAUDITTRAIL ADJ with(nolock)  ON ADJ.APNO = A.APNO AND ADJ.SECTIONID = EM.EMPLID
INNER JOIN REFAFFILIATE RF with(nolock)  ON RF.AFFILIATEID = C.AFFILIATEID
INNER JOIN SECTSTAT SS with(nolock)  ON SS.CODE = EM.SECTSTAT
INNER JOIN CLIENTADJUDICATIONSTATUS CADJ  with(nolock) ON CADJ.CLIENTADJUDICATIONSTATUSID = EM.CLIENTADJUDICATIONSTATUS
left JOIN CLIENTADJUDICATIONSTATUSCUSTOM CADJC with(nolock)  ON CADJC.CLIENTADJUDICATIONSTATUSID = CADJ.CLIENTADJUDICATIONSTATUSID AND CADJ.CLNO = A.CLNO
LEFT JOIN DBO.SectSubStatus SSS  with(nolock) ON EM.SectStat = SSS.SectStatusCode AND EM.SectSubStatusID = SSS.SectSubStatusID
WHERE (A.APDATE BETWEEN @STARTDATE AND @ENDDATE)
AND A.CLNO = IIF(@CLNO=0,A.CLNO,@CLNO)
--AND C.AFFILIATEID = IIF(@AFFILIATEID=0, C.AFFILIATEID, @AFFILIATEID)--code commented by vairavan for ticket id -53763
		 and (@AffiliateIDs IS NULL OR c.AffiliateID IN (SELECT value FROM fn_Split(@AffiliateIDs,':')))--code added by vairavan for ticket id -53763
GROUP BY A.APNO, C.CLNO, C.NAME, A.LAST, A.FIRST, A.INVESTIGATOR, A.APDATE, A.COMPDATE, A.USERID,
EM.Employer,CADJ.DESCRIPTION, ADJ.REVIEWDATE_CAM,ADJ.REVIEWDATE_MGR, EM.ISHIDDEN, EM.ISONREPORT, RF.AFFILIATE,SS.DESCRIPTION, ISNULL(sss.SectSubStatus,'')


UNION ALL

--STEP 3 : ADJUDICATION BY COMPONENT - LICENSE

SELECT C.CLNO, C.NAME, A.APNO, A.LAST, A.FIRST, A.INVESTIGATOR, A.APDATE, A.COMPDATE,
A.USERID, 'LICENSE' AS 'COMPONENT TYPE', PL.LIC_TYPE AS 'COMPONENT DATA', SS.DESCRIPTION AS 'COMPONENT STATUS',ISNULL(sss.SectSubStatus,'') AS 'COMPONENT SUBSTATUS', CADJ.DESCRIPTION AS 'ADJUDICATIONSTATUS',
(CASE WHEN ADJ.REVIEWDATE_CAM IS NULL THEN 'FALSE' ELSE 'TRUE' END ) AS 'CAM BOX',
(CASE WHEN ADJ.REVIEWDATE_MGR IS NULL THEN 'FALSE' ELSE 'TRUE' END ) AS 'MGR BOX',
(CASE PL.ISHIDDEN WHEN 1 THEN 'UNUSED' ELSE 'ON REPORT' END ) AS ISHIDDEN,
(CASE PL.ISONREPORT WHEN 1 THEN 'YES' ELSE 'UNUSED' END ) AS ISONREPORT, RF.AFFILIATE
FROM APPL A with(nolock) 
INNER JOIN CLIENT C  with(nolock) ON C.CLNO = A.CLNO
INNER JOIN PROFLIC PL with(nolock)  ON PL.APNO = A.APNO 
INNER JOIN APPLADJUDICATIONAUDITTRAIL ADJ with(nolock)  ON ADJ.APNO = A.APNO AND ADJ.SECTIONID = PL.PROFLICID
INNER JOIN REFAFFILIATE RF  with(nolock) ON RF.AFFILIATEID = C.AFFILIATEID
INNER JOIN SECTSTAT SS with(nolock)  ON SS.CODE = PL.SECTSTAT
INNER JOIN CLIENTADJUDICATIONSTATUS CADJ  with(nolock) ON CADJ.CLIENTADJUDICATIONSTATUSID = PL.CLIENTADJUDICATIONSTATUS
left JOIN CLIENTADJUDICATIONSTATUSCUSTOM  CADJC with(nolock) ON CADJC.CLIENTADJUDICATIONSTATUSID = CADJ.CLIENTADJUDICATIONSTATUSID AND CADJ.CLNO = A.CLNO
LEFT JOIN DBO.SectSubStatus SSS  with(nolock) ON PL.SectStat = SSS.SectStatusCode AND PL.SectSubStatusID = SSS.SectSubStatusID
WHERE (A.APDATE BETWEEN @STARTDATE AND @ENDDATE)
AND A.CLNO = IIF(@CLNO=0,A.CLNO,@CLNO)
--AND C.AFFILIATEID = IIF(@AFFILIATEID=0, C.AFFILIATEID, @AFFILIATEID)--code commented by vairavan for ticket id -53763
		 and (@AffiliateIDs IS NULL OR c.AffiliateID IN (SELECT value FROM fn_Split(@AffiliateIDs,':')))--code added by vairavan for ticket id -53763
GROUP BY A.APNO, C.CLNO, C.NAME, A.LAST, A.FIRST, A.INVESTIGATOR, A.APDATE, A.COMPDATE, A.USERID,
PL.LIC_TYPE,CADJ.DESCRIPTION, ADJ.REVIEWDATE_CAM,ADJ.REVIEWDATE_MGR, PL.ISHIDDEN, PL.ISONREPORT, RF.AFFILIATE,SS.DESCRIPTION,ISNULL(sss.SectSubStatus,'')
  
	
UNION ALL


--STEP 4 : ADJUDICATION BY COMPONENT - PERSONAL REFERENCE

SELECT C.CLNO, C.NAME, A.APNO, A.LAST, A.FIRST, A.INVESTIGATOR, A.APDATE, A.COMPDATE,
A.USERID, 'PERSONAL REFERENCE' AS 'COMPONENT TYPE', PR.NAME AS 'COMPONENT DATA',SS.DESCRIPTION AS 'COMPONENT STATUS',ISNULL(sss.SectSubStatus,'') AS 'COMPONENT SUBSTATUS',CADJ.DESCRIPTION AS 'ADJUDICATIONSTATUS',
(CASE WHEN ADJ.REVIEWDATE_CAM IS NULL THEN 'FALSE' ELSE 'TRUE' END ) AS 'CAM BOX',
(CASE WHEN ADJ.REVIEWDATE_MGR IS NULL THEN 'FALSE' ELSE 'TRUE' END ) AS 'MGR BOX',
(CASE PR.ISHIDDEN WHEN 1 THEN 'UNUSED' ELSE 'ON REPORT' END ) AS ISHIDDEN,
(CASE PR.ISONREPORT WHEN 1 THEN 'YES' ELSE 'UNUSED' END ) AS ISONREPORT, RF.AFFILIATE
FROM APPL A with(nolock) 
INNER JOIN CLIENT C  with(nolock) ON C.CLNO = A.CLNO
INNER JOIN PERSREF PR  with(nolock) ON PR.APNO = A.APNO 
INNER JOIN APPLADJUDICATIONAUDITTRAIL ADJ with(nolock)  ON ADJ.APNO = A.APNO AND ADJ.SECTIONID = PR.PERSREFID
INNER JOIN REFAFFILIATE RF with(nolock)  ON RF.AFFILIATEID = C.AFFILIATEID
INNER JOIN SECTSTAT SS  with(nolock) ON SS.CODE = PR.SECTSTAT
INNER JOIN CLIENTADJUDICATIONSTATUS CADJ  with(nolock) ON CADJ.CLIENTADJUDICATIONSTATUSID = PR.CLIENTADJUDICATIONSTATUS
left JOIN CLIENTADJUDICATIONSTATUSCUSTOM CADJC with(nolock)  ON CADJC.CLIENTADJUDICATIONSTATUSID = CADJ.CLIENTADJUDICATIONSTATUSID AND CADJ.CLNO = A.CLNO
LEFT JOIN DBO.SectSubStatus SSS  with(nolock) ON PR.SectStat = SSS.SectStatusCode AND PR.SectSubStatusID = SSS.SectSubStatusID
WHERE (A.APDATE BETWEEN @STARTDATE AND @ENDDATE)
AND A.CLNO = IIF(@CLNO=0,A.CLNO,@CLNO)
--AND C.AFFILIATEID = IIF(@AFFILIATEID=0, C.AFFILIATEID, @AFFILIATEID)--code commented by vairavan for ticket id -53763
		 and (@AffiliateIDs IS NULL OR c.AffiliateID IN (SELECT value FROM fn_Split(@AffiliateIDs,':')))--code added by vairavan for ticket id -53763
GROUP BY A.APNO, C.CLNO, C.NAME, A.LAST, A.FIRST, A.INVESTIGATOR, A.APDATE, A.COMPDATE, A.USERID,
PR.NAME,CADJ.DESCRIPTION, ADJ.REVIEWDATE_CAM,ADJ.REVIEWDATE_MGR, PR.ISHIDDEN, PR.ISONREPORT, RF.AFFILIATE,SS.DESCRIPTION,ISNULL(sss.SectSubStatus,'')


UNION ALL


--STEP 5 : ADJUDICATION BY COMPONENT - CRIMINAL

SELECT C.CLNO, C.NAME, A.APNO, A.LAST, A.FIRST, A.INVESTIGATOR, A.APDATE, A.COMPDATE, 
A.USERID, 'CRIMINAL' AS 'COMPONENT TYPE', CR.COUNTY AS 'COMPONENT DATA', CSS.CRIMDESCRIPTION AS 'COMPONENT STATUS','' AS 'COMPONENT SUBSTATUS', CADJ.DESCRIPTION AS 'ADJUDICATIONSTATUS', 
(CASE WHEN ADJ.REVIEWDATE_CAM IS NULL THEN 'FALSE' ELSE 'TRUE' END ) AS 'CAM BOX',
(CASE WHEN ADJ.REVIEWDATE_MGR IS NULL THEN 'FALSE' ELSE 'TRUE' END ) AS 'MGR BOX',
(CASE CR.ISHIDDEN WHEN 1 THEN 'UNUSED' ELSE 'ON REPORT' END ) AS ISHIDDEN,
NULL AS 'ISONREPORT', RF.AFFILIATE
FROM APPL A with(nolock) 
INNER JOIN CLIENT C  with(nolock) ON C.CLNO = A.CLNO
INNER JOIN CRIM CR  with(nolock) ON CR.APNO = A.APNO 
LEFT JOIN APPLADJUDICATIONAUDITTRAIL ADJ with(nolock)  ON ADJ.APNO = A.APNO AND ADJ.SECTIONID = CR.CRIMID
INNER JOIN REFAFFILIATE RF  with(nolock) ON RF.AFFILIATEID = C.AFFILIATEID
INNER JOIN Crimsectstat CSS  with(nolock) ON CSS.crimsect = CR.[Clear] 
INNER JOIN CLIENTADJUDICATIONSTATUS CADJ  with(nolock) ON CADJ.CLIENTADJUDICATIONSTATUSID = CR.CLIENTADJUDICATIONSTATUS
left JOIN CLIENTADJUDICATIONSTATUSCUSTOM CADJC  with(nolock) ON CADJC.CLIENTADJUDICATIONSTATUSID = CADJ.CLIENTADJUDICATIONSTATUSID AND CADJ.CLNO = A.CLNO
WHERE (A.APDATE BETWEEN @STARTDATE AND @ENDDATE)
AND A.CLNO = IIF(@CLNO=0,A.CLNO,@CLNO)
--AND C.AFFILIATEID = IIF(@AFFILIATEID=0, C.AFFILIATEID, @AFFILIATEID)--code commented by vairavan for ticket id -53763
		 and (@AffiliateIDs IS NULL OR c.AffiliateID IN (SELECT value FROM fn_Split(@AffiliateIDs,':')))--code added by vairavan for ticket id -53763
GROUP BY A.APNO, C.CLNO, C.NAME, A.LAST, A.FIRST, A.INVESTIGATOR, A.APDATE, A.COMPDATE, A.USERID,
CR.COUNTY,CADJ.DESCRIPTION, ADJ.REVIEWDATE_CAM,ADJ.REVIEWDATE_MGR, CR.ISHIDDEN, RF.AFFILIATE,CSS.CRIMDESCRIPTION


UNION ALL


--STEP 6 : ADJUDICATION BY COMPONENT - SANCTIONS

SELECT C.CLNO, C.NAME, A.APNO, A.LAST, A.FIRST, A.INVESTIGATOR, A.APDATE, A.COMPDATE, 
A.USERID, 'SANCTIONS' AS 'COMPONENT TYPE', 'SANCTIONS' AS 'COMPONENT DATA',SS.DESCRIPTION AS 'COMPONENT STATUS','' AS 'COMPONENT SUBSTATUS', CADJ.DESCRIPTION AS 'ADJUDICATIONSTATUS', 
(CASE WHEN ADJ.REVIEWDATE_CAM IS NULL THEN 'FALSE' ELSE 'TRUE' END ) AS 'CAM BOX',
(CASE WHEN ADJ.REVIEWDATE_MGR IS NULL THEN 'FALSE' ELSE 'TRUE' END ) AS 'MGR BOX',
(CASE MI.ISHIDDEN WHEN 1 THEN 'UNUSED' ELSE 'ON REPORT' END ) AS ISHIDDEN,
NULL AS 'ISONREPORT', RF.AFFILIATE
FROM APPL A with(nolock) 
INNER JOIN CLIENT C  with(nolock) ON C.CLNO = A.CLNO
INNER JOIN MEDINTEG MI with(nolock)  ON MI.APNO = A.APNO 
INNER JOIN APPLADJUDICATIONAUDITTRAIL ADJ with(nolock)  ON ADJ.APNO = A.APNO AND ADJ.ApplSectionID = 7
INNER JOIN REFAFFILIATE RF with(nolock)  ON RF.AFFILIATEID = C.AFFILIATEID
INNER JOIN SECTSTAT SS  with(nolock) ON SS.CODE = MI.SECTSTAT
INNER JOIN CLIENTADJUDICATIONSTATUS CADJ  with(nolock) ON CADJ.CLIENTADJUDICATIONSTATUSID = MI.CLIENTADJUDICATIONSTATUS
left JOIN CLIENTADJUDICATIONSTATUSCUSTOM CADJC  with(nolock)  ON CADJC.CLIENTADJUDICATIONSTATUSID = CADJ.CLIENTADJUDICATIONSTATUSID AND CADJ.CLNO = A.CLNO
WHERE (A.APDATE BETWEEN @STARTDATE AND @ENDDATE)
AND A.CLNO = IIF(@CLNO=0,A.CLNO,@CLNO)
--AND C.AFFILIATEID = IIF(@AFFILIATEID=0, C.AFFILIATEID, @AFFILIATEID)--code commented by vairavan for ticket id -53763
		 and (@AffiliateIDs IS NULL OR c.AffiliateID IN (SELECT value FROM fn_Split(@AffiliateIDs,':')))--code added by vairavan for ticket id -53763
GROUP BY A.APNO, C.CLNO, C.NAME, A.LAST, A.FIRST, A.INVESTIGATOR, A.APDATE, A.COMPDATE, A.USERID,
CADJ.DESCRIPTION, ADJ.REVIEWDATE_CAM,ADJ.REVIEWDATE_MGR, MI.ISHIDDEN, RF.AFFILIATE,SS.DESCRIPTION


UNION ALL


--STEP 7 : ADJUDICATION BY COMPONENT - POSITIVE ID

SELECT C.CLNO, C.NAME, A.APNO, A.LAST, A.FIRST, A.INVESTIGATOR, A.APDATE, A.COMPDATE,
A.USERID, 'POSITIVE ID' AS 'COMPONENT TYPE', 'POSITIVE ID' AS 'COMPONENT DATA',SS.DESCRIPTION AS 'COMPONENT STATUS','' AS 'COMPONENT SUBSTATUS', CADJ.DESCRIPTION AS 'ADJUDICATIONSTATUS',
(CASE WHEN ADJ.REVIEWDATE_CAM IS NULL THEN 'FALSE' ELSE 'TRUE' END ) AS 'CAM BOX',
(CASE WHEN ADJ.REVIEWDATE_MGR IS NULL THEN 'FALSE' ELSE 'TRUE' END ) AS 'MGR BOX',
(CASE CD.ISHIDDEN WHEN 1 THEN 'UNUSED' ELSE 'ON REPORT' END ) AS ISHIDDEN,
NULL AS 'ISONREPORT', RF.AFFILIATE
FROM APPL A with(nolock) 
INNER JOIN CLIENT C  with(nolock) ON C.CLNO = A.CLNO
INNER JOIN CREDIT CD  with(nolock) ON CD.APNO = A.APNO 
INNER JOIN APPLADJUDICATIONAUDITTRAIL ADJ with(nolock)  ON ADJ.APNO = A.APNO AND ADJ.ApplSectionID = 9
INNER JOIN REFAFFILIATE RF with(nolock)  ON RF.AFFILIATEID = C.AFFILIATEID
INNER JOIN SECTSTAT SS with(nolock)  ON SS.CODE = CD.SECTSTAT
INNER JOIN CLIENTADJUDICATIONSTATUS CADJ with(nolock)  ON CADJ.CLIENTADJUDICATIONSTATUSID = CD.CLIENTADJUDICATIONSTATUS
left JOIN CLIENTADJUDICATIONSTATUSCUSTOM CADJC  with(nolock) ON CADJC.CLIENTADJUDICATIONSTATUSID = CADJ.CLIENTADJUDICATIONSTATUSID AND CADJ.CLNO = A.CLNO
WHERE (A.APDATE BETWEEN @STARTDATE AND @ENDDATE)
AND A.CLNO = IIF(@CLNO=0,A.CLNO,@CLNO)
--AND C.AFFILIATEID = IIF(@AFFILIATEID=0, C.AFFILIATEID, @AFFILIATEID)--code commented by vairavan for ticket id -53763
		 and (@AffiliateIDs IS NULL OR c.AffiliateID IN (SELECT value FROM fn_Split(@AffiliateIDs,':')))--code added by vairavan for ticket id -53763
GROUP BY A.APNO, C.CLNO, C.NAME, A.LAST, A.FIRST, A.INVESTIGATOR, A.APDATE, A.COMPDATE, A.USERID,
CADJ.DESCRIPTION, ADJ.REVIEWDATE_CAM,ADJ.REVIEWDATE_MGR,CD.ISHIDDEN, RF.AFFILIATE,SS.DESCRIPTION

END

