CREATE TABLE [dbo].['2052845808$'] (
    [Invoice Number]            FLOAT (53)     NULL,
    [Cust #]                    FLOAT (53)     NULL,
    [Product Description]       NVARCHAR (255) NULL,
    [Transaction Description]   NVARCHAR (255) NULL,
    [Date]                      DATETIME       NULL,
    [Time]                      DATETIME       NULL,
    [UnitPrice]                 FLOAT (53)     NULL,
    [Quantity]                  FLOAT (53)     NULL,
    [Extended]                  FLOAT (53)     NULL,
    [State]                     NVARCHAR (255) NULL,
    [AuthorizedUser#]           NVARCHAR (255) NULL,
    [Reference/Ext Ord #]       FLOAT (53)     NULL,
    [Source]                    NVARCHAR (255) NULL,
    [Tracking]                  NVARCHAR (255) NULL,
    [UserID]                    NVARCHAR (255) NULL,
    [Cost Center]               NVARCHAR (255) NULL,
    [Cost Center Name]          NVARCHAR (255) NULL,
    [Branch/Division]           FLOAT (53)     NULL,
    [Branch Name/Division Name] NVARCHAR (255) NULL,
    [Lenderid]                  NVARCHAR (255) NULL,
    [Verifier ID]               FLOAT (53)     NULL,
    [VerifierName]              NVARCHAR (255) NULL,
    [Company Code]              FLOAT (53)     NULL,
    [Borrower]                  NVARCHAR (255) NULL,
    [Loan Number Manual]        NVARCHAR (255) NULL,
    [Request ID]                NVARCHAR (255) NULL,
    [Loan Number Instant]       NVARCHAR (255) NULL,
    [Cost Center Spectrum]      NVARCHAR (255) NULL,
    [SSN/EIN]                   NVARCHAR (255) NULL,
    [Consumer Firstname]        NVARCHAR (255) NULL,
    [Borrower Status]           NVARCHAR (255) NULL,
    [Master Reference Number]   NVARCHAR (255) NULL,
    [End User]                  NVARCHAR (255) NULL,
    [End User Name]             NVARCHAR (255) NULL
);

