CREATE TABLE [dbo].[15989AllData] (
    [Client ID]      FLOAT (53)     NULL,
    [Dept]           NVARCHAR (255) NULL,
    [Last Name]      NVARCHAR (255) NULL,
    [First Name]     NVARCHAR (255) NULL,
    [M#N#]           NVARCHAR (255) NULL,
    [DOB]            NVARCHAR (255) NULL,
    [L#N#]           NVARCHAR (255) NULL,
    [D#L#]           NVARCHAR (255) NULL,
    [CAM]            NVARCHAR (255) NULL,
    [Investigator]   NVARCHAR (255) NULL,
    [SSN]            NVARCHAR (255) NULL,
    [1]              NVARCHAR (255) NULL,
    [2]              NVARCHAR (255) NULL,
    [3]              NVARCHAR (255) NULL,
    [4]              NVARCHAR (255) NULL,
    [5]              NVARCHAR (255) NULL,
    [Private Notes]  NVARCHAR (255) NULL,
    [11]             NVARCHAR (255) NULL,
    [21]             NVARCHAR (255) NULL,
    [31]             NVARCHAR (255) NULL,
    [41]             NVARCHAR (255) NULL,
    [51]             NVARCHAR (255) NULL,
    [6]              NVARCHAR (255) NULL,
    [7]              NVARCHAR (255) NULL,
    [8]              NVARCHAR (255) NULL,
    [9]              NVARCHAR (255) NULL,
    [10]             NVARCHAR (255) NULL,
    [School]         NVARCHAR (255) NULL,
    [CampusLocation] NVARCHAR (255) NULL,
    [City]           NVARCHAR (255) NULL,
    [State]          NVARCHAR (255) NULL,
    [Studies]        NVARCHAR (255) NULL,
    [F33]            NVARCHAR (255) NULL,
    [F34]            NVARCHAR (255) NULL
);

