CREATE TABLE [dbo].[BillingDetails_CARCO_ByMonth] (
    [ID]                       INT             IDENTITY (1, 1) NOT NULL,
    [Revenue_date]             DATETIME        NOT NULL,
    [clientgrp]                VARCHAR (200)   NULL,
    [leadtype]                 VARCHAR (100)   NULL,
    [subtype]                  VARCHAR (100)   NULL,
    [CARCO_Fees]               SMALLMONEY      NULL,
    [Pass_Through_Fees]        SMALLMONEY      NULL,
    [numcases]                 DECIMAL (18, 2) NULL,
    [numleads]                 INT             NULL,
    [numbusdays]               INT             NULL,
    [numbusdays_in_month]      INT             NULL,
    [Volume per Business Day]  DECIMAL (18, 2) NULL,
    [Revenue per Business Day] DECIMAL (18, 2) NULL,
    [YEAR]                     INT             NOT NULL,
    [Month]                    INT             NOT NULL,
    [Value]                    SMALLMONEY      NULL,
    [BUSINESS UNIT]            VARCHAR (100)   NULL,
    [CUSTOMER]                 VARCHAR (200)   NULL,
    [CUSTOMER GROUP]           VARCHAR (200)   NULL,
    [INDUSTRY]                 VARCHAR (100)   NULL,
    [COUNTRY]                  VARCHAR (50)    NULL,
    [CUSTOMER/VENDOR]          VARCHAR (50)    NULL,
    [RETAIL/WHOLESALE]         VARCHAR (50)    NULL,
    [CIP LEVEL 1 PRODUCT]      VARCHAR (50)    NULL,
    [CIP LEVEL 2 PRODUCT]      VARCHAR (50)    NULL,
    [RECURRING/NON-RECURRING]  VARCHAR (50)    NULL,
    [CLNO]                     INT             NULL,
    [InvoiceNumber]            INT             NULL,
    [BillingCycle]             VARCHAR (10)    NULL,
    [Total]                    SMALLMONEY      NULL,
    CONSTRAINT [PKBillingDetails_CARCO_ByMonth_ID] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 50)
);

