CREATE TABLE [dbo].[Boncrim] (
    [Client ID]            FLOAT (53)     NULL,
    [Department]           NVARCHAR (255) NULL,
    [Last Name]            NVARCHAR (255) NULL,
    [First Name]           NVARCHAR (255) NULL,
    [Middle]               NVARCHAR (255) NULL,
    [Date of Birth]        NVARCHAR (255) NULL,
    [License Number]       NVARCHAR (255) NULL,
    [DL_State]             NVARCHAR (255) NULL,
    [CAM]                  NVARCHAR (255) NULL,
    [Investigator]         NVARCHAR (255) NULL,
    [SSN]                  NVARCHAR (255) NULL,
    [Address1]             NVARCHAR (255) NULL,
    [Address2]             NVARCHAR (255) NULL,
    [city]                 NVARCHAR (255) NULL,
    [State]                NVARCHAR (255) NULL,
    [Zip]                  NVARCHAR (255) NULL,
    [PrivateNotes]         NVARCHAR (255) NULL,
    [ClientAPNO]           NVARCHAR (255) NULL,
    [Attn]                 NVARCHAR (255) NULL,
    [Licensetype]          NVARCHAR (255) NULL,
    [LicenseNumber]        NVARCHAR (255) NULL,
    [LicenseState]         NVARCHAR (255) NULL,
    [Licensetype2]         NVARCHAR (255) NULL,
    [LicenseNumber2]       NVARCHAR (255) NULL,
    [LicenseState2]        NVARCHAR (255) NULL,
    [ApplicantPhone]       NVARCHAR (255) NULL,
    [ApplicantEmail]       NVARCHAR (255) NULL,
    [SchoolName]           NVARCHAR (255) NULL,
    [SchoolCampusLocation] NVARCHAR (255) NULL,
    [SchoolCity]           NVARCHAR (255) NULL,
    [SchoolState]          NVARCHAR (255) NULL,
    [Degree]               NVARCHAR (255) NULL,
    [School_From]          NVARCHAR (255) NULL,
    [School_To]            NVARCHAR (255) NULL,
    [NameOnGraduation]     NVARCHAR (255) NULL,
    [School_Notes]         NVARCHAR (255) NULL,
    [PackageID]            FLOAT (53)     NULL,
    [Pos_Sought]           NVARCHAR (255) NULL,
    [Studies]              NVARCHAR (255) NULL
);

