CREATE TABLE [dbo].[ClientEmployer] (
    [ClientEmployerID]      INT           IDENTITY (1, 1) NOT NULL,
    [Company]               VARCHAR (120) NOT NULL,
    [MainPhone]             VARCHAR (50)  NULL,
    [Phone]                 VARCHAR (50)  NULL,
    [Phone2]                VARCHAR (50)  NULL,
    [Fax]                   VARCHAR (50)  NULL,
    [FirstName]             VARCHAR (50)  NULL,
    [LastName]              VARCHAR (50)  NULL,
    [Title]                 VARCHAR (50)  NULL,
    [Email]                 VARCHAR (50)  NULL,
    [Address]               VARCHAR (50)  NULL,
    [City]                  VARCHAR (30)  NULL,
    [State]                 VARCHAR (2)   NULL,
    [Zip]                   VARCHAR (20)  NULL,
    [Country]               VARCHAR (20)  NULL,
    [Comment]               TEXT          NULL,
    [Comment2]              TEXT          NULL,
    [IsClient]              BIT           NOT NULL,
    [CLNO]                  INT           NULL,
    [EmplContactMethod]     INT           NOT NULL,
    [PreferredInvestigator] VARCHAR (20)  NULL,
    [EmplReleaseRequired]   BIT           NULL,
    [Deleted]               BIT           NOT NULL,
    [LastUpdate]            DATETIME      NULL,
    [CreatedDate]           DATETIME      NULL,
    [KeyName]               VARCHAR (8)   NULL,
    [WorkNumberID]          INT           NULL,
    [AliasList]             VARCHAR (MAX) NULL,
    [ExternalReferenceIDs]  VARCHAR (500) NULL,
    CONSTRAINT [PK_ClientEmployer] PRIMARY KEY CLUSTERED ([ClientEmployerID] ASC)
) TEXTIMAGE_ON [PRIMARY];

