CREATE TABLE [dbo].[Client_kiran] (
    [CLNO]                           SMALLINT      NOT NULL,
    [Name]                           VARCHAR (100) NULL,
    [Addr1]                          VARCHAR (100) NULL,
    [Addr2]                          VARCHAR (100) NULL,
    [Addr3]                          VARCHAR (25)  NULL,
    [City]                           VARCHAR (50)  NULL,
    [State]                          VARCHAR (20)  NULL,
    [Zip]                            VARCHAR (20)  NULL,
    [Phone]                          VARCHAR (20)  NULL,
    [Fax]                            VARCHAR (20)  NULL,
    [Contact]                        VARCHAR (25)  NULL,
    [Email]                          VARCHAR (35)  NULL,
    [HomeCounty]                     VARCHAR (25)  NULL,
    [TaxRate]                        SMALLMONEY    NULL,
    [Status]                         CHAR (1)      NOT NULL,
    [BillCycle]                      CHAR (2)      NOT NULL,
    [FirstApdate]                    DATETIME      NULL,
    [LastInvDate]                    DATETIME      NULL,
    [LastInvAmount]                  SMALLMONEY    NULL,
    [CNTY_NO]                        INT           NULL,
    [AffiliateID]                    INT           NULL,
    [CAM]                            VARCHAR (8)   NULL,
    [TeamID]                         INT           NULL,
    [Investigator1]                  VARCHAR (8)   NULL,
    [Investigator2]                  VARCHAR (8)   NULL,
    [HighProfile]                    BIT           NULL,
    [CountyCrimID]                   INT           NULL,
    [CountyCrimNotesID]              INT           NULL,
    [StateCrimNotesID]               INT           NULL,
    [Social]                         BIT           NULL,
    [MVR]                            VARCHAR (50)  NULL,
    [Medicaid/Medicare]              BIT           NULL,
    [EmploymentID]                   INT           NULL,
    [EmploymentNotes1ID]             INT           NULL,
    [EmploymentNotes2ID]             INT           NULL,
    [EducationNotesID]               INT           NULL,
    [LicenseNotesID]                 INT           NULL,
    [CreditNotesID]                  INT           NULL,
    [PersonalRefNotes]               VARCHAR (50)  NULL,
    [Comments]                       TEXT          NULL,
    [DeliveryMethodID]               INT           NULL,
    [BillingCycleID]                 INT           NULL,
    [BillingStatusID]                INT           NULL,
    [IsInactive]                     BIT           NOT NULL,
    [IsOnCreditHold]                 BIT           NOT NULL,
    [AttnTo]                         VARCHAR (50)  NULL,
    [BillingAddress1]                VARCHAR (50)  NULL,
    [BillingAddress2]                VARCHAR (50)  NULL,
    [BillingCity]                    VARCHAR (30)  NULL,
    [BillingState]                   VARCHAR (20)  NULL,
    [BillingZip]                     VARCHAR (20)  NULL,
    [PrintLabel]                     BIT           NULL,
    [TaxStatusID]                    INT           NULL,
    [TaxRateID]                      INT           NULL,
    [IsTaxExempt]                    BIT           NOT NULL,
    [TaxExemptionNumber]             VARCHAR (15)  NULL,
    [TaxExempVerifiedDate]           DATETIME      NULL,
    [TaxExemptVerifiedUserID]        VARCHAR (8)   NULL,
    [TaxLocaleID]                    INT           NULL,
    [SalesPersonUserID]              VARCHAR (8)   NULL,
    [CustomerRatingID]               INT           NULL,
    [HolidayGift]                    BIT           NULL,
    [password]                       VARCHAR (20)  NULL,
    [HEVNEmployerStatusID]           INT           NOT NULL,
    [HEVNEmployerInternal]           BIT           NULL,
    [HEVNPayrollNotes]               VARCHAR (500) NULL,
    [ParentCLNO]                     SMALLINT      NULL,
    [CompanyLogoPath]                VARCHAR (100) NULL,
    [NonClient]                      BIT           NULL,
    [DescriptiveName]                VARCHAR (100) NULL,
    [Medical]                        BIT           NULL,
    [OneCountyPricing]               BIT           NULL,
    [OneCountyPrice]                 MONEY         NULL,
    [LmsEmployer]                    BIT           NULL,
    [Lms_FileGrouping_Preference]    VARCHAR (50)  NULL,
    [LmsLetter1]                     INT           NULL,
    [LmsLetter2]                     INT           NULL,
    [LmsLetter3]                     INT           NULL,
    [LmsInitialCleanupDone]          BIT           NULL,
    [LmsInitialCleanupDoneDateStamp] DATETIME      NULL,
    [LmsCanPrintCertificates]        BIT           NULL,
    [EmplEmployerNotes]              TEXT          NULL,
    [EmplClientNotes]                TEXT          NULL,
    [AppTrackerEmployer]             BIT           NULL,
    [Adverse]                        INT           NULL,
    [CertificateLetter1]             INT           NULL,
    [CertificateLetter2]             INT           NULL,
    [ClientEntry]                    DATETIME      NULL,
    [UserAgreementDate]              DATETIME      NULL,
    [AutoReportDelivery]             BIT           NULL,
    [ClientTypeID]                   INT           NULL,
    [CredentCheckCam]                VARCHAR (50)  NULL,
    [WebOrderParentCLNO]             INT           NULL,
    [IsOnSchoolDroplist]             BIT           NULL,
    [EmplInvestigatorByClient1]      VARCHAR (8)   NULL,
    [EmplInvestigatorByClient2]      VARCHAR (8)   NULL,
    [PersRefInvestigator1]           VARCHAR (8)   NULL,
    [PersRefInvestigator2]           VARCHAR (8)   NULL,
    [GetsEmpl_StudentCheck]          BIT           NOT NULL,
    [GetsProfLic_StudentCheck]       BIT           NOT NULL,
    [SchoolWillPay]                  BIT           NOT NULL,
    [AgreementIsRequired]            BIT           NOT NULL,
    [AutoLinkHospitals]              BIT           NOT NULL,
    [AreNewLicensesSeparate]         BIT           NOT NULL,
    [CredentCheckEmployerStatusID]   INT           NULL,
    [LmsAutomateRunClosures]         BIT           NOT NULL,
    [GetsEdu_StudentCheck]           BIT           NOT NULL,
    [EduInvestigator1]               VARCHAR (8)   NULL,
    [EduInvestigator2]               VARCHAR (8)   NULL,
    [OKtoContact]                    BIT           NULL,
    [EmplInvestigatorByClient3]      VARCHAR (8)   NULL,
    [EmplInvestigatorByClient4]      VARCHAR (8)   NULL,
    [EmplInvestigatorByEmployer1]    VARCHAR (8)   NULL,
    [EmplInvestigatorByEmployer2]    VARCHAR (8)   NULL,
    [IsNameMismatchADeficiency]      BIT           NOT NULL,
    [WebSite]                        VARCHAR (250) NULL,
    [CreatedDate]                    DATETIME      NULL,
    [MVRService]                     BIT           NOT NULL,
    [MvrID]                          INT           NULL,
    [AffiliateID_PO]                 INT           NULL,
    [ZipCrimClientID]                VARCHAR (6)   NULL,
    [Accounting System Grouping]     VARCHAR (200) NULL,
    [Customer-Vendor]                VARCHAR (200) NULL,
    [Revenue Frequency]              VARCHAR (200) NULL
) TEXTIMAGE_ON [PRIMARY];

