CREATE TABLE [dbo].[ClientStatusCredentCheck] (
    [ClientStatusCredentCheckID]        INT           IDENTITY (1, 1) NOT NULL,
    [ClientName]                        VARCHAR (100) NULL,
    [ClientStatusCredentClientParentID] INT           NULL,
    [CLNO]                              INT           NULL,
    [Stage]                             INT           NULL,
    [Priority]                          INT           NULL,
    [NumberOfLicenses]                  INT           NULL,
    [Notes]                             VARCHAR (200) NULL,
    [Contact]                           VARCHAR (50)  NULL,
    [GoLiveDate]                        DATETIME      NULL,
    [RunTypeID]                         VARCHAR (50)  NULL,
    [NumberTotal]                       INT           NULL,
    [NumberRemaining]                   INT           NULL,
    [DueDate]                           DATETIME      NULL,
    [UpdatedOn]                         DATETIME      NULL,
    [UpdatedBy]                         VARCHAR (50)  NULL,
    [HEVNdataNotes]                     VARCHAR (500) NULL,
    [SendsHevn]                         BIT           CONSTRAINT [DF__ClientSta__Sends__4D9552F2] DEFAULT (0) NULL,
    [SendsTerm]                         BIT           CONSTRAINT [DF__ClientSta__Sends__4E89772B] DEFAULT (0) NOT NULL,
    [SendsNewHire]                      BIT           CONSTRAINT [DF__ClientSta__Sends__4F7D9B64] DEFAULT (0) NOT NULL,
    [HEVN]                              BIT           CONSTRAINT [DF__ClientStat__HEVN__5071BF9D] DEFAULT (0) NOT NULL,
    [CredentCheck]                      BIT           CONSTRAINT [DF__ClientSta__Crede__5165E3D6] DEFAULT (0) NOT NULL,
    [TradeRehire]                       BIT           CONSTRAINT [DF__ClientSta__Trade__525A080F] DEFAULT (0) NOT NULL,
    [PriorityTask]                      VARCHAR (100) NULL,
    [LastUpdated]                       DATETIME      NULL,
    [NextEvent]                         VARCHAR (100) NULL,
    [AreLicensesMapped]                 BIT           DEFAULT (0) NOT NULL,
    [AreJobTitleRequirementsSet]        BIT           DEFAULT (0) NOT NULL,
    [HEVNdataDate]                      DATETIME      NULL,
    [LicenseDataDate]                   DATETIME      NULL,
    [LicenseDataNotes]                  VARCHAR (100) NULL,
    [NewHireDataDate]                   DATETIME      NULL,
    [NewHireDataNotes]                  VARCHAR (100) NULL,
    [TermDataDate]                      DATETIME      NULL,
    [TermDataNotes]                     VARCHAR (100) NULL,
    [HevnYears]                         INT           NULL,
    CONSTRAINT [PK_ClientStatusCredentCheck] PRIMARY KEY CLUSTERED ([ClientStatusCredentCheckID] ASC) WITH (FILLFACTOR = 50)
);

