CREATE TABLE [dbo].[DecDSDownloadableBillingFile] (
    [InvoiceID]      NVARCHAR (255) NULL,
    [bill-code]      NVARCHAR (255) NULL,
    [cust no]        NVARCHAR (255) NULL,
    [Cust Name]      NVARCHAR (255) NULL,
    [grup-no]        NVARCHAR (255) NULL,
    [Group]          NVARCHAR (255) NULL,
    [loc-no]         NVARCHAR (255) NULL,
    [Loc Name]       NVARCHAR (255) NULL,
    [prod-code]      NVARCHAR (255) NULL,
    [date-svc]       NVARCHAR (255) NULL,
    [amt-bill]       NVARCHAR (255) NULL,
    [empl-no]        NVARCHAR (255) NULL,
    [name]           NVARCHAR (255) NULL,
    [spec-no]        NVARCHAR (255) NULL,
    [coc-no]         NVARCHAR (255) NULL,
    [test-code]      NVARCHAR (255) NULL,
    [BgState]        NVARCHAR (255) NULL,
    [Tier]           NVARCHAR (255) NULL,
    [Spec Type]      NVARCHAR (255) NULL,
    [transaction id] NVARCHAR (255) NULL,
    [Comments]       NVARCHAR (255) NULL,
    [Cost Center]    NVARCHAR (255) NULL,
    [Job Code]       NVARCHAR (255) NULL
);

