CREATE TABLE [dbo].[EducationCredentials] (
    [EducationCredentialID] INT           IDENTITY (1, 1) NOT NULL,
    [StagingApplicantId]    INT           NOT NULL,
    [SchoolName]            VARCHAR (50)  NOT NULL,
    [City]                  VARCHAR (50)  NULL,
    [State]                 VARCHAR (2)   NULL,
    [Zipcode]               CHAR (5)      NULL,
    [Phone]                 VARCHAR (20)  NULL,
    [Degree]                VARCHAR (100) NULL,
    [Major]                 VARCHAR (25)  NULL,
    [Minor]                 VARCHAR (25)  NULL,
    [StartDate]             VARCHAR (30)  NULL,
    [EndDate]               VARCHAR (30)  NULL,
    [Notes]                 VARCHAR (MAX) NULL,
    [HasGraduated]          BIT           DEFAULT ((0)) NULL,
    [GraduationDate]        VARCHAR (30)  NULL,
    [GPA]                   VARCHAR (10)  NULL,
    [GPAScale]              VARCHAR (50)  NULL,
    [SchoolType]            VARCHAR (50)  NULL,
    [HadResidedAtAddress]   BIT           NULL,
    [CredentialSource]      VARCHAR (20)  NOT NULL,
    [CreatedBy]             VARCHAR (50)  NULL,
    [CreatedDate]           DATETIME      CONSTRAINT [DF_EducationCredentials_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [LastModifiedDate]      DATETIME      CONSTRAINT [DF_EducationCredentials_LastModifiedDate] DEFAULT (getdate()) NOT NULL,
    [LastModifiedBy]        VARCHAR (20)  NULL,
    [Country]               VARCHAR (50)  NULL,
    [RecipientFirstName]    VARCHAR (100) NULL,
    [RecipientMiddleName]   VARCHAR (100) NULL,
    [RecipientLastName]     VARCHAR (100) NULL,
    CONSTRAINT [PK_EducationCredentials] PRIMARY KEY CLUSTERED ([EducationCredentialID] ASC)
);

