CREATE TABLE [dbo].[EmplGetNextStaging] (
    [EmplGetNextStagingID] INT           IDENTITY (1, 1) NOT NULL,
    [APNO]                 INT           NULL,
    [EmplID]               INT           NULL,
    [Employer]             VARCHAR (30)  NULL,
    [EmployerID]           INT           NULL,
    [ApDate]               DATETIME      NULL,
    [IsOnReport]           BIT           NULL,
    [Rush]                 BIT           NULL,
    [SectStat]             CHAR (1)      NULL,
    [ApStatus]             CHAR (1)      NULL,
    [web_status]           INT           NULL,
    [OkToContact]          BIT           NULL,
    [HighProfile]          BIT           NULL,
    [PrecheckChallenge]    BIT           NULL,
    [Affiliate]            VARCHAR (50)  NULL,
    [CLNO]                 INT           NULL,
    [ClientName]           VARCHAR (100) NULL,
    [Investigator]         VARCHAR (8)   NULL,
    [Last_Updated]         DATETIME      NULL,
    [ApplInUse]            VARCHAR (8)   NULL,
    [EmplInvestigatorID1]  VARCHAR (8)   NULL,
    [EmplInvestigatorID2]  VARCHAR (8)   NULL,
    [EmplInvestigatorID3]  VARCHAR (8)   NULL,
    [EmplInvestigatorID4]  VARCHAR (8)   NULL,
    [ApplicationTimeZone]  VARCHAR (20)  NULL,
    [TimeZone]             VARCHAR (20)  CONSTRAINT [DF_EmplGetNextStaging_TimeZone] DEFAULT ('Central') NULL,
    [QueueType]            VARCHAR (50)  NULL,
    [TransitionalState]    VARCHAR (10)  NULL,
    [AppPickedUpDate]      DATETIME      NULL,
    [StagingRunDate]       DATETIME      NULL,
    [FollowUpOn]           DATETIME      NULL,
    [SectSubStatusID]      INT           NULL,
    CONSTRAINT [PK_EmplGetNextStaging] PRIMARY KEY CLUSTERED ([EmplGetNextStagingID] ASC) WITH (FILLFACTOR = 50)
);

