CREATE TABLE [dbo].[EmploymentCredentials] (
    [EmploymentCredentialID] INT           IDENTITY (1, 1) NOT NULL,
    [StagingApplicantId]     INT           NOT NULL,
    [EmployerID]             INT           NULL,
    [CompanyName]            VARCHAR (100) NOT NULL,
    [Address]                VARCHAR (250) NULL,
    [City]                   VARCHAR (50)  NULL,
    [State]                  CHAR (2)      NULL,
    [Zipcode]                CHAR (5)      NULL,
    [Phone]                  VARCHAR (20)  NULL,
    [Email]                  VARCHAR (50)  NULL,
    [Supervisor]             VARCHAR (25)  NULL,
    [SupervisorTitle]        VARCHAR (25)  NULL,
    [SupPhone]               VARCHAR (20)  NULL,
    [Department]             VARCHAR (30)  NULL,
    [RFL]                    VARCHAR (30)  NULL,
    [DNC]                    BIT           CONSTRAINT [DF_EmploymentCredentials_DNC] DEFAULT ((0)) NULL,
    [IsMilitary]             BIT           NULL,
    [IsOnUnemployment]       BIT           NULL,
    [IsEligibleForRehire]    BIT           NULL,
    [IsCurrentEmployer]      BIT           NULL,
    [IsSelfEmployed]         BIT           NULL,
    [StartingSalary]         VARCHAR (15)  NULL,
    [FinalSalary]            VARCHAR (15)  NULL,
    [StartingCommission]     VARCHAR (50)  NULL,
    [FinalCommission]        VARCHAR (50)  NULL,
    [StartingBonus]          VARCHAR (50)  NULL,
    [FinalBonus]             VARCHAR (50)  NULL,
    [HireDate]               VARCHAR (30)  NULL,
    [SearationDate]          VARCHAR (30)  NULL,
    [LastPosition]           VARCHAR (50)  NULL,
    [Notes]                  VARCHAR (MAX) NULL,
    [EmploymentTypes]        VARCHAR (50)  NULL,
    [CredentialSource]       VARCHAR (20)  NOT NULL,
    [CreatedBy]              VARCHAR (50)  NULL,
    [CreatedDate]            DATETIME      CONSTRAINT [DF_EmploymentCredentials_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [LastModifiedDate]       DATETIME      CONSTRAINT [DF_EmploymentCredentials_LastModifiedDate] DEFAULT (getdate()) NOT NULL,
    [LastModifiedBy]         VARCHAR (20)  NULL,
    [Country]                VARCHAR (50)  NULL,
    [RecipientFirstName]     VARCHAR (100) NULL,
    [RecipientMiddleName]    VARCHAR (100) NULL,
    [RecipientLastName]      VARCHAR (100) NULL,
    CONSTRAINT [PK_EmploymentCredentials] PRIMARY KEY CLUSTERED ([EmploymentCredentialID] ASC)
);

