CREATE TABLE [dbo].[eVerifileIssues06242020_2] (
    [ClientGrp]         NVARCHAR (255) NULL,
    [ClientID]          NVARCHAR (255) NULL,
    [CT]                NVARCHAR (255) NULL,
    [SubmDate]          NVARCHAR (255) NULL,
    [ Name ]            NVARCHAR (255) NULL,
    [CaseNum]           NVARCHAR (255) NULL,
    [LN]                NVARCHAR (255) NULL,
    [LeadType]          NVARCHAR (255) NULL,
    [SubType]           NVARCHAR (255) NULL,
    [SubType2]          NVARCHAR (255) NULL,
    [LeadStart]         NVARCHAR (255) NULL,
    [LeadDays]          FLOAT (53)     NULL,
    [Process]           NVARCHAR (255) NULL,
    [Step]              NVARCHAR (255) NULL,
    [ StepDescription ] NVARCHAR (255) NULL,
    [Step_start]        NVARCHAR (255) NULL,
    [ETA]               NVARCHAR (255) NULL,
    [EtaDays]           FLOAT (53)     NULL,
    [EtaSet]            NVARCHAR (255) NULL,
    [ EtaUser ]         NVARCHAR (255) NULL,
    [ EtaReason ]       NVARCHAR (255) NULL,
    [ Description ]     NVARCHAR (255) NULL,
    [rpt_days]          NVARCHAR (255) NULL
);

