CREATE TABLE [dbo].[HCA_HR_ProcessLevels_02242016] (
    [Wave]                                                             NVARCHAR (255) NULL,
    [Active EEs]                                                       NVARCHAR (255) NULL,
    [EE Counts]                                                        FLOAT (53)     NULL,
    [Division]                                                         NVARCHAR (255) NULL,
    [Taleo Org]                                                        NVARCHAR (255) NULL,
    [Future Taleo Org]                                                 NVARCHAR (255) NULL,
    [HR Company]                                                       FLOAT (53)     NULL,
    [Process Level]                                                    VARCHAR (10)   NULL,
    [Process Level Desc]                                               NVARCHAR (255) NULL,
    [(Use this shared email box for ALL inquiries,escalations and adj] NVARCHAR (255) NULL,
    [City]                                                             NVARCHAR (255) NULL,
    [State]                                                            NVARCHAR (255) NULL,
    [Zip]                                                              FLOAT (53)     NULL,
    [Status]                                                           NVARCHAR (255) NULL,
    [LOB]                                                              NVARCHAR (255) NULL,
    [FEIN]                                                             NVARCHAR (255) NULL,
    [Group]                                                            NVARCHAR (255) NULL,
    [Market]                                                           NVARCHAR (255) NULL,
    [Div VP HR]                                                        NVARCHAR (255) NULL,
    [VP HR (Use this column for PSG Provider adjudication only)]       NVARCHAR (255) NULL,
    [Sr HRBP]                                                          NVARCHAR (255) NULL,
    [HRBP]                                                             NVARCHAR (255) NULL,
    [HR Coord]                                                         NVARCHAR (255) NULL,
    [PSG ILOB HR Dir]                                                  NVARCHAR (255) NULL,
    [Compensation Lead]                                                NVARCHAR (255) NULL,
    [Recruiting Team]                                                  NVARCHAR (255) NULL,
    [PreBoarding Coordinator]                                          NVARCHAR (255) NULL,
    [DIV CSO]                                                          NVARCHAR (255) NULL,
    [DIV CFO]                                                          NVARCHAR (255) NULL
);

