CREATE TABLE [dbo].[Iris_SearchesOrdered] (
    [SearchesOrderedID]        INT          IDENTITY (1, 1) NOT NULL,
    [APNO]                     INT          NULL,
    [Last]                     VARCHAR (20) NULL,
    [First]                    VARCHAR (20) NULL,
    [Middle]                   VARCHAR (20) NULL,
    [Ordered]                  DATETIME     NULL,
    [CrimID]                   INT          NULL,
    [CNTY_NO]                  INT          NULL,
    [R_id]                     INT          NULL,
    [R_Name]                   VARCHAR (50) NULL,
    [txtlast]                  CHAR (2)     NULL,
    [txtalias]                 CHAR (2)     NULL,
    [txtalias2]                CHAR (2)     NULL,
    [txtalias3]                CHAR (2)     NULL,
    [txtalias4]                CHAR (2)     NULL,
    [Researcher_Fel]           MONEY        NULL,
    [Researcher_Mis]           MONEY        NULL,
    [Researcher_fed]           MONEY        NULL,
    [Researcher_alias]         MONEY        NULL,
    [Researcher_combo]         MONEY        NULL,
    [Researcher_other]         MONEY        NULL,
    [Researcher_CourtFees]     MONEY        NULL,
    [Researcher_Aliases_count] VARCHAR (4)  NULL,
    [TotalCharges]             MONEY        NULL,
    [ActualCharges]            MONEY        NULL,
    [Cancel]                   DATETIME     NULL,
    CONSTRAINT [PK_Iris_SearchesOrdered] PRIMARY KEY CLUSTERED ([SearchesOrderedID] ASC) WITH (FILLFACTOR = 50)
);

