CREATE TABLE [dbo].[MVR_Import] (
    [MVR_ImportID]         SMALLINT       IDENTITY (1, 1) NOT NULL,
    [Client ID]            SMALLINT       NULL,
    [Department]           VARCHAR (50)   NULL,
    [Last Name]            VARCHAR (50)   NULL,
    [First Name]           VARCHAR (50)   NULL,
    [Middle]               VARCHAR (50)   NULL,
    [Date of Birth]        DATETIME       NULL,
    [License Number]       VARCHAR (20)   NULL,
    [DL_State]             CHAR (2)       NULL,
    [CAM]                  VARCHAR (8)    NULL,
    [Investigator]         VARCHAR (8)    NULL,
    [SSN]                  VARCHAR (11)   NULL,
    [Address1]             VARCHAR (70)   NULL,
    [Address2]             VARCHAR (30)   NULL,
    [city]                 VARCHAR (20)   NULL,
    [State]                CHAR (2)       NULL,
    [Zip]                  VARCHAR (10)   NULL,
    [PrivateNotes]         VARCHAR (1000) NULL,
    [ClientAPNO]           VARCHAR (50)   NULL,
    [Attn]                 VARCHAR (25)   NULL,
    [Licensetype]          VARCHAR (30)   NULL,
    [LicenseNumber]        VARCHAR (20)   NULL,
    [LicenseState]         VARCHAR (8)    NULL,
    [Licensetype2]         VARCHAR (30)   NULL,
    [LicenseNumber2]       VARCHAR (20)   NULL,
    [LicenseState2]        VARCHAR (8)    NULL,
    [ApplicantPhone]       VARCHAR (15)   NULL,
    [ApplicantEmail]       VARCHAR (50)   NULL,
    [SchoolName]           VARCHAR (50)   NULL,
    [SchoolCampusLocation] VARCHAR (50)   NULL,
    [SchoolCity]           VARCHAR (50)   NULL,
    [SchoolState]          VARCHAR (2)    NULL,
    [Degree]               VARCHAR (50)   NULL,
    [School_From]          VARCHAR (50)   NULL,
    [School_To]            VARCHAR (50)   NULL,
    [NameOnGraduation]     VARCHAR (50)   NULL,
    [School_Notes]         VARCHAR (100)  NULL,
    [PackageID]            SMALLINT       NULL,
    [Pos_Sought]           VARCHAR (100)  NULL,
    [Studies]              VARCHAR (100)  NULL
) ON [PRIMARY];

