CREATE TABLE [dbo].[PrecheckFramework_PersRefStaging] (
    [PersRefStagingID]         INT            IDENTITY (19325, 1) NOT NULL,
    [SectionId]                INT            NULL,
    [FolderId]                 VARCHAR (50)   NULL,
    [APNO]                     INT            NULL,
    [SectStat]                 CHAR (1)       NULL,
    [Worksheet]                BIT            NULL,
    [Name]                     VARCHAR (25)   NULL,
    [Phone]                    VARCHAR (20)   NULL,
    [Rel_V]                    VARCHAR (50)   NULL,
    [Years_V]                  SMALLINT       NULL,
    [Priv_Notes]               NVARCHAR (MAX) NULL,
    [Pub_Notes]                NVARCHAR (MAX) NULL,
    [Last_Updated]             DATETIME       NULL,
    [Investigator]             VARCHAR (8)    NULL,
    [Emplid]                   INT            NULL,
    [PendingUpdated]           DATETIME       NULL,
    [Web_Status]               INT            NULL,
    [web_updated]              DATETIME       NULL,
    [time_in]                  DATETIME       NULL,
    [InUse]                    VARCHAR (20)   NULL,
    [CreatedDate]              DATETIME       NULL,
    [Last_Worked]              DATETIME       NULL,
    [IsCAMReview]              BIT            NULL,
    [IsOnReport]               BIT            NULL,
    [IsHidden]                 BIT            NULL,
    [IsHistoryRecord]          BIT            NULL,
    [ClientAdjudicationStatus] INT            NULL,
    [Email]                    VARCHAR (50)   NULL,
    [JobTitle]                 VARCHAR (100)  NULL,
    CONSTRAINT [PK_PersRefStage] PRIMARY KEY CLUSTERED ([PersRefStagingID] ASC)
) TEXTIMAGE_ON [PRIMARY];

