CREATE TABLE [dbo].[PrecheckFramework_EducatStaging] (
    [EducatStagingId]          INT            IDENTITY (19337, 1) NOT NULL,
    [SectionId]                INT            NULL,
    [FolderId]                 VARCHAR (50)   NULL,
    [APNO]                     INT            NULL,
    [School]                   VARCHAR (50)   NULL,
    [SectStat]                 CHAR (1)       NULL,
    [Worksheet]                BIT            NULL,
    [State]                    VARCHAR (2)    NULL,
    [Phone]                    VARCHAR (20)   NULL,
    [Degree_A]                 VARCHAR (50)   NULL,
    [Studies_A]                VARCHAR (25)   NULL,
    [From_A]                   VARCHAR (12)   NULL,
    [To_A]                     VARCHAR (12)   NULL,
    [Name]                     VARCHAR (100)  NULL,
    [Degree_V]                 VARCHAR (50)   NULL,
    [Studies_V]                VARCHAR (25)   NULL,
    [From_V]                   VARCHAR (12)   NULL,
    [To_V]                     VARCHAR (12)   NULL,
    [Contact_Name]             VARCHAR (30)   NULL,
    [Contact_Title]            VARCHAR (30)   NULL,
    [Contact_Date]             DATETIME       NULL,
    [Investigator]             VARCHAR (30)   NULL,
    [Priv_Notes]               NVARCHAR (MAX) NULL,
    [Pub_Notes]                NVARCHAR (MAX) NULL,
    [web_status]               INT            NULL,
    [includealias]             CHAR (1)       NULL,
    [includealias2]            CHAR (1)       NULL,
    [includealias3]            CHAR (1)       NULL,
    [includealias4]            CHAR (1)       NULL,
    [pendingupdated]           DATETIME       NULL,
    [web_updated]              DATETIME       NULL,
    [Time_In]                  DATETIME       NULL,
    [Last_Updated]             DATETIME       NULL,
    [city]                     VARCHAR (50)   NULL,
    [zipcode]                  CHAR (5)       NULL,
    [CampusName]               VARCHAR (25)   NULL,
    [InUse]                    VARCHAR (20)   NULL,
    [CreatedDate]              DATETIME       NULL,
    [ToPending]                DATETIME       NULL,
    [FromPending]              DATETIME       NULL,
    [Completed]                BIT            NULL,
    [Last_Worked]              DATETIME       NULL,
    [SchoolID]                 INT            NULL,
    [IsCAMReview]              BIT            NULL,
    [IsOnReport]               BIT            NULL,
    [IsHidden]                 BIT            NULL,
    [IsHistoryRecord]          BIT            NULL,
    [HasGraduated]             BIT            NULL,
    [HighestCompleted]         VARCHAR (50)   NULL,
    [EducatVerifyID]           INT            NULL,
    [GetNextDate]              DATETIME       NULL,
    [SubStatusID]              INT            NULL,
    [ClientAdjudicationStatus] INT            NULL,
    [ClientRefID]              VARCHAR (25)   NULL,
    [IsIntl]                   BIT            NULL,
    [DateOrdered]              DATETIME       NULL,
    [OrderId]                  VARCHAR (20)   NULL,
    [City_V]                   VARCHAR (50)   NULL,
    [State_V]                  VARCHAR (20)   NULL,
    [Country_V]                VARCHAR (50)   NULL,
    [RecipientName_V]          VARCHAR (150)  NULL,
    [GraduationDate_V]         DATETIME       NULL,
    CONSTRAINT [PK_StagEducat] PRIMARY KEY CLUSTERED ([EducatStagingId] ASC)
) TEXTIMAGE_ON [PRIMARY];

