CREATE TABLE [dbo].[PrecheckFramework_ProfLicStaging] (
    [ProfLicStagingID]              INT            IDENTITY (36980, 1) NOT NULL,
    [FolderId]                      VARCHAR (50)   NULL,
    [SectionId]                     INT            NULL,
    [Apno]                          INT            NULL,
    [SectStat]                      CHAR (1)       NULL,
    [Worksheet]                     BIT            NULL,
    [Lic_Type]                      VARCHAR (100)  NULL,
    [Lic_No]                        VARCHAR (20)   NULL,
    [Year]                          VARCHAR (10)   NULL,
    [Expire]                        DATETIME       NULL,
    [State]                         VARCHAR (8)    NULL,
    [Status]                        VARCHAR (20)   NULL,
    [Priv_Notes]                    NVARCHAR (MAX) NULL,
    [Pub_Notes]                     NVARCHAR (MAX) NULL,
    [Web_status]                    INT            NULL,
    [includealias]                  CHAR (1)       NULL,
    [includealias2]                 CHAR (1)       NULL,
    [includealias3]                 CHAR (1)       NULL,
    [includealias4]                 CHAR (1)       NULL,
    [pendingupdated]                DATETIME       NULL,
    [web_updated]                   DATETIME       NULL,
    [time_in]                       DATETIME       NULL,
    [Organization]                  VARCHAR (30)   NULL,
    [Contact_Name]                  VARCHAR (30)   NULL,
    [Contact_Title]                 VARCHAR (30)   NULL,
    [Contact_Date]                  DATETIME       NULL,
    [Investigator]                  VARCHAR (30)   NULL,
    [Last_Updated]                  DATETIME       NULL,
    [InUse]                         VARCHAR (20)   NULL,
    [CreatedDate]                   DATETIME       NULL,
    [Status_A]                      VARCHAR (20)   NULL,
    [ToPending]                     DATETIME       NULL,
    [FromPending]                   DATETIME       NULL,
    [Last_Worked]                   DATETIME       NULL,
    [IsCAMReview]                   BIT            NULL,
    [IsOnReport]                    BIT            NULL,
    [IsHidden]                      BIT            NULL,
    [IsHistoryRecord]               BIT            NULL,
    [ClientAdjudicationStatus]      INT            NULL,
    [ClientRefID]                   VARCHAR (25)   NULL,
    [Lic_Type_V]                    VARCHAR (100)  NULL,
    [Lic_No_V]                      VARCHAR (20)   NULL,
    [State_V]                       VARCHAR (8)    NULL,
    [Expire_V]                      DATETIME       NULL,
    [Year_V]                        VARCHAR (10)   NULL,
    [GenerateCertificate]           BIT            NULL,
    [CertificateAvailabilityStatus] INT            NULL,
    [DisclosedPastAction]           BIT            NULL,
    [LicenseTypeID]                 INT            NULL,
    [NameOnLicense_V]               VARCHAR (200)  NULL,
    [Speciality_V]                  VARCHAR (50)   NULL,
    [LifeTime_V]                    BIT            NULL,
    [BoardActions_V]                VARCHAR (10)   NULL,
    [ContactMethod_V]               VARCHAR (50)   NULL,
    [InUse_TimeStamp]               DATETIME       NULL,
    CONSTRAINT [PK_ProfLicStg] PRIMARY KEY CLUSTERED ([ProfLicStagingID] ASC)
) TEXTIMAGE_ON [PRIMARY];

