CREATE TABLE [dbo].[PrecheckFramework_ApplStaging] (
    [ApplStagingId]           INT            IDENTITY (167110, 1) NOT NULL,
    [APNO]                    INT            NOT NULL,
    [FolderId]                VARCHAR (50)   NOT NULL,
    [ApStatus]                CHAR (1)       NULL,
    [UserID]                  VARCHAR (8)    NULL,
    [FollowUpDuration]        INT            NULL,
    [Billed]                  BIT            NULL,
    [Investigator]            VARCHAR (20)   NULL,
    [EnteredBy]               VARCHAR (20)   NULL,
    [EnteredVia]              VARCHAR (8)    NULL,
    [ApDate]                  DATETIME       NULL,
    [CompDate]                DATETIME       NULL,
    [CLNO]                    SMALLINT       NOT NULL,
    [Attn]                    VARCHAR (100)  NULL,
    [Last]                    VARCHAR (50)   NULL,
    [First]                   VARCHAR (50)   NULL,
    [Middle]                  VARCHAR (50)   NULL,
    [Alias]                   VARCHAR (30)   NULL,
    [Alias2]                  VARCHAR (30)   NULL,
    [Alias3]                  VARCHAR (30)   NULL,
    [Alias4]                  VARCHAR (30)   NULL,
    [SSN]                     VARCHAR (11)   NULL,
    [DOB]                     DATETIME       NULL,
    [Sex]                     VARCHAR (1)    NULL,
    [DL_State]                VARCHAR (2)    NULL,
    [DL_Number]               VARCHAR (20)   NULL,
    [Addr_Num]                VARCHAR (6)    NULL,
    [Addr_Dir]                VARCHAR (2)    NULL,
    [Addr_Street]             VARCHAR (100)  NULL,
    [Addr_StType]             VARCHAR (2)    NULL,
    [Addr_Apt]                VARCHAR (5)    NULL,
    [City]                    VARCHAR (50)   NULL,
    [State]                   VARCHAR (2)    NULL,
    [Zip]                     VARCHAR (5)    NULL,
    [Pos_Sought]              VARCHAR (100)  NULL,
    [Update_Billing]          BIT            NULL,
    [Priv_Notes]              NVARCHAR (MAX) NULL,
    [Pub_Notes]               NVARCHAR (MAX) NULL,
    [PC_Time_Stamp]           DATETIME       NULL,
    [Pc_Time_Out]             DATETIME       NULL,
    [Special_instructions]    NVARCHAR (MAX) NULL,
    [Reason]                  CHAR (20)      NULL,
    [ReopenDate]              DATETIME       NULL,
    [OrigCompDate]            DATETIME       NULL,
    [Generation]              VARCHAR (3)    NULL,
    [Alias1_Last]             VARCHAR (50)   NULL,
    [Alias1_First]            VARCHAR (50)   NULL,
    [Alias1_Middle]           VARCHAR (50)   NULL,
    [Alias1_Generation]       VARCHAR (3)    NULL,
    [Alias2_Last]             VARCHAR (50)   NULL,
    [Alias2_First]            VARCHAR (50)   NULL,
    [Alias2_Middle]           VARCHAR (50)   NULL,
    [Alias2_Generation]       VARCHAR (3)    NULL,
    [Alias3_Last]             VARCHAR (50)   NULL,
    [Alias3_First]            VARCHAR (50)   NULL,
    [Alias3_Middle]           VARCHAR (50)   NULL,
    [Alias3_Generation]       VARCHAR (3)    NULL,
    [Alias4_Last]             VARCHAR (50)   NULL,
    [Alias4_First]            VARCHAR (50)   NULL,
    [Alias4_Middle]           VARCHAR (50)   NULL,
    [Alias4_Generation]       VARCHAR (3)    NULL,
    [PrecheckChallenge]       BIT            NULL,
    [InUse]                   VARCHAR (20)   NULL,
    [ClientAPNO]              VARCHAR (50)   NULL,
    [ClientApplicantNO]       VARCHAR (50)   NULL,
    [Last_Updated]            DATETIME       NULL,
    [DeptCode]                VARCHAR (20)   NULL,
    [NeedsReview]             VARCHAR (2)    NULL,
    [StartDate]               DATETIME       NULL,
    [RecruiterID]             INT            NULL,
    [Phone]                   VARCHAR (50)   NULL,
    [Rush]                    BIT            NULL,
    [IsAutoPrinted]           BIT            NULL,
    [AutoPrintedDate]         DATETIME       NULL,
    [IsAutoSent]              BIT            NULL,
    [AutoSentDate]            DATETIME       NULL,
    [PackageID]               SMALLINT       NULL,
    [Rel_Attached]            BIT            NULL,
    [CreatedDate]             DATETIME       NULL,
    [ClientProgramID]         INT            NULL,
    [I94]                     VARCHAR (50)   NULL,
    [Recruiter_Email]         VARCHAR (50)   NULL,
    [CAM]                     VARCHAR (8)    NULL,
    [SubStatusID]             INT            NULL,
    [GetNextDate]             DATETIME       NULL,
    [Email]                   VARCHAR (100)  NULL,
    [CellPhone]               VARCHAR (20)   NULL,
    [OtherPhone]              VARCHAR (20)   NULL,
    [IsDrugTestFileFound_bit] BIT            NULL,
    [IsDrugTestFileFound]     INT            NULL,
    [FreeReport]              BIT            NULL,
    CONSTRAINT [PK_StgAppl] PRIMARY KEY CLUSTERED ([APNO] ASC) WITH (FILLFACTOR = 70)
);

