CREATE TABLE [dbo].[PrecheckFramework_EmplStaging] (
    [EmplStagingId]            INT            IDENTITY (1, 1) NOT NULL,
    [SectionID]                INT            NULL,
    [Apno]                     INT            NULL,
    [FolderId]                 VARCHAR (50)   NULL,
    [Employer]                 VARCHAR (30)   NULL,
    [Location]                 VARCHAR (250)  NULL,
    [SectStat]                 CHAR (1)       NULL,
    [Worksheet]                BIT            NULL,
    [Phone]                    VARCHAR (20)   NULL,
    [Supervisor]               VARCHAR (25)   NULL,
    [SupPhone]                 VARCHAR (20)   NULL,
    [Dept]                     VARCHAR (30)   NULL,
    [RFL]                      VARCHAR (30)   NULL,
    [DNC]                      BIT            NULL,
    [SpecialQ]                 BIT            NULL,
    [Ver_Salary]               BIT            NULL,
    [From_A]                   VARCHAR (12)   NULL,
    [To_A]                     VARCHAR (12)   NULL,
    [Position_A]               VARCHAR (50)   NULL,
    [Salary_A]                 VARCHAR (15)   NULL,
    [From_V]                   VARCHAR (30)   NULL,
    [To_V]                     VARCHAR (30)   NULL,
    [Position_V]               VARCHAR (50)   NULL,
    [Salary_V]                 VARCHAR (50)   NULL,
    [Emp_Type]                 CHAR (1)       NULL,
    [Rel_Cond]                 CHAR (1)       NULL,
    [Rehire]                   VARCHAR (1)    NULL,
    [Ver_By]                   VARCHAR (50)   NULL,
    [Title]                    VARCHAR (50)   NULL,
    [Priv_Notes]               NVARCHAR (MAX) NULL,
    [Pub_Notes]                NVARCHAR (MAX) NULL,
    [web_status]               INT            NULL,
    [web_updated]              DATETIME       NULL,
    [Includealias]             CHAR (1)       NULL,
    [Includealias2]            CHAR (1)       NULL,
    [Includealias3]            CHAR (1)       NULL,
    [Includealias4]            CHAR (1)       NULL,
    [PendingUpdated]           DATETIME       NULL,
    [Time_In]                  DATETIME       NULL,
    [Last_Updated]             DATETIME       NULL,
    [city]                     VARCHAR (50)   NULL,
    [state]                    CHAR (2)       NULL,
    [zipcode]                  CHAR (5)       NULL,
    [Investigator]             VARCHAR (8)    NULL,
    [EmployerID]               INT            NULL,
    [InvestigatorAssigned]     DATETIME       NULL,
    [PendingChanged]           DATETIME       NULL,
    [TempInvestigator]         VARCHAR (10)   NULL,
    [InUse]                    VARCHAR (20)   NULL,
    [CreatedDate]              DATETIME       NULL,
    [EnteredBy]                VARCHAR (50)   NULL,
    [EnteredDate]              DATETIME       NULL,
    [IsCamReview]              BIT            NULL,
    [Last_Worked]              DATETIME       NULL,
    [ClientEmployerID]         INT            NULL,
    [AutoFaxStatus]            INT            NULL,
    [IsOnReport]               BIT            NULL,
    [IsHidden]                 BIT            NULL,
    [IsHistoryRecord]          BIT            NULL,
    [EmploymentStatus]         VARCHAR (50)   NULL,
    [IsOKtoContact]            BIT            NULL,
    [OKtoContactInitial]       VARCHAR (15)   NULL,
    [EmplVerifyID]             INT            NULL,
    [GetNextDate]              DATETIME       NULL,
    [SubStatusID]              INT            NULL,
    [ClientAdjudicationStatus] INT            NULL,
    [ClientRefID]              VARCHAR (25)   NULL,
    [IsIntl]                   BIT            NULL,
    [DateOrdered]              DATETIME       NULL,
    [OrderId]                  VARCHAR (20)   NULL,
    [AdverseRFL]               BIT            NULL,
    [Email]                    VARCHAR (50)   NULL,
    [City_V]                   VARCHAR (50)   NULL,
    [State_V]                  VARCHAR (20)   NULL,
    [Country_V]                VARCHAR (50)   NULL,
    [RecipientName_V]          VARCHAR (150)  NULL,
    CONSTRAINT [PK_PrecheckFramework_EmplStaging] PRIMARY KEY CLUSTERED ([EmplStagingId] ASC)
) TEXTIMAGE_ON [PRIMARY];

