CREATE TABLE [dbo].[RemovePO] (
    [ExternalID]                  FLOAT (53)     NULL,
    [Customer ID]                 NVARCHAR (255) NULL,
    [Individual]                  NVARCHAR (255) NULL,
    [Company Name]                NVARCHAR (255) NULL,
    [Subsidiary]                  NVARCHAR (255) NULL,
    [Represents Subsidiary]       NVARCHAR (255) NULL,
    [Email]                       NVARCHAR (255) NULL,
    [Phone]                       NVARCHAR (255) NULL,
    [Status]                      NVARCHAR (255) NULL,
    [Sales Rep]                   NVARCHAR (255) NULL,
    [Child Of]                    NVARCHAR (255) NULL,
    [Category]                    NVARCHAR (255) NULL,
    [Inactive]                    NVARCHAR (255) NULL,
    [Primary Currency]            NVARCHAR (255) NULL,
    [Terms]                       NVARCHAR (255) NULL,
    [Taxable]                     NVARCHAR (255) NULL,
    [Tax Reg# Number]             FLOAT (53)     NULL,
    [Label]                       NVARCHAR (255) NULL,
    [Attention]                   NVARCHAR (255) NULL,
    [Addressee]                   NVARCHAR (255) NULL,
    [Phone2]                      NVARCHAR (255) NULL,
    [PO#]                         NVARCHAR (255) NULL,
    [Address 1]                   NVARCHAR (255) NULL,
    [Address 2]                   NVARCHAR (255) NULL,
    [City]                        NVARCHAR (255) NULL,
    [Province/State]              NVARCHAR (255) NULL,
    [Postal Code/Zip]             NVARCHAR (255) NULL,
    [Country]                     NVARCHAR (255) NULL,
    [Default Billing]             NVARCHAR (255) NULL,
    [Default Shipping]            NVARCHAR (255) NULL,
    [Email Preference]            NVARCHAR (255) NULL,
    [Invoice Email Addresses]     NVARCHAR (255) NULL,
    [Customer/Vendor]             NVARCHAR (255) NULL,
    [Retail/Wholesale]            NVARCHAR (255) NULL,
    [Accounting System Grouping]  NVARCHAR (255) NULL,
    [Revenue Type]                NVARCHAR (255) NULL,
    [BillingCycle]                NVARCHAR (255) NULL,
    [PartnerId]                   NVARCHAR (255) NULL,
    [Default Receivables Account] NVARCHAR (255) NULL
);

