CREATE TABLE [dbo].[RolodexReviewLic] (
    [RolodexReviewLicID]    INT           IDENTITY (1, 1) NOT NULL,
    [CreatedDate]           DATETIME      NULL,
    [CreatedBy]             VARCHAR (25)  NULL,
    [ReviewType]            VARCHAR (8)   NULL,
    [LicenseType]           VARCHAR (200) NULL,
    [RegType]               VARCHAR (80)  NULL,
    [Organization]          VARCHAR (200) NULL,
    [Contact]               VARCHAR (50)  NULL,
    [AutomatedPhone]        VARCHAR (50)  NULL,
    [Phone]                 VARCHAR (50)  NULL,
    [Phone2]                VARCHAR (50)  NULL,
    [Fax]                   VARCHAR (50)  NULL,
    [Address]               VARCHAR (255) NULL,
    [City]                  VARCHAR (50)  NULL,
    [State]                 VARCHAR (30)  NULL,
    [Zip]                   VARCHAR (30)  NULL,
    [Country]               VARCHAR (50)  NULL,
    [Location]              VARCHAR (50)  NULL,
    [WebPage]               VARCHAR (255) NULL,
    [Email]                 VARCHAR (80)  NULL,
    [Note]                  TEXT          NULL,
    [CLNO]                  INT           NULL,
    [Status]                VARCHAR (20)  NULL,
    [Supervisor]            VARCHAR (20)  NULL,
    [RolodexLicenseID]      INT           NULL,
    [refLicContactMethodID] INT           NULL,
    CONSTRAINT [PK_RolodexReviewLic] PRIMARY KEY CLUSTERED ([RolodexReviewLicID] ASC) WITH (FILLFACTOR = 90)
) TEXTIMAGE_ON [PRIMARY];

