CREATE TABLE [dbo].[RolodexReviewEdu] (
    [RolodexReviewEduID] INT           IDENTITY (1, 1) NOT NULL,
    [CreatedDate]        SMALLDATETIME NULL,
    [CreatedBy]          VARCHAR (25)  NULL,
    [ReviewType]         VARCHAR (8)   NULL,
    [School]             VARCHAR (120) NULL,
    [Initials]           VARCHAR (30)  NULL,
    [Fax]                VARCHAR (30)  NULL,
    [Phone]              VARCHAR (30)  NULL,
    [RegistrarPhone]     VARCHAR (30)  NULL,
    [Email]              VARCHAR (255) NULL,
    [WebPage]            VARCHAR (500) NULL,
    [Address]            VARCHAR (100) NULL,
    [City]               VARCHAR (30)  NULL,
    [State]              VARCHAR (2)   NULL,
    [Zip]                VARCHAR (20)  NULL,
    [Country]            VARCHAR (30)  NULL,
    [Note]               TEXT          NULL,
    [CLNO]               INT           NULL,
    [ContactMethod]      INT           NULL,
    [ReleaseRequired]    BIT           NULL,
    [NCHID]              VARCHAR (30)  NULL,
    [RolodexEducationID] INT           NULL,
    [Supervisor]         VARCHAR (20)  NULL,
    [Status]             VARCHAR (20)  NULL,
    [ContactName]        VARCHAR (75)  NULL,
    [ContactTitle]       VARCHAR (75)  NULL,
    [FaxToAttnOf]        VARCHAR (75)  NULL,
    [AlternateFax]       VARCHAR (30)  NULL,
    CONSTRAINT [PK_RolodexReviewEdu] PRIMARY KEY CLUSTERED ([RolodexReviewEduID] ASC)
) TEXTIMAGE_ON [PRIMARY];

