CREATE TABLE [dbo].[RolodexReview] (
    [ReviewID]              INT           IDENTITY (1, 1) NOT NULL,
    [CreatedDate]           SMALLDATETIME NULL,
    [CreatedBy]             VARCHAR (25)  NULL,
    [ReviewType]            VARCHAR (8)   NULL,
    [Company]               VARCHAR (120) NULL,
    [First]                 VARCHAR (50)  NULL,
    [Last]                  VARCHAR (50)  NULL,
    [Addr]                  VARCHAR (50)  NULL,
    [City]                  VARCHAR (30)  NULL,
    [State]                 VARCHAR (2)   NULL,
    [Zip]                   VARCHAR (20)  NULL,
    [Country]               VARCHAR (20)  NULL,
    [MainPhone]             VARCHAR (50)  NULL,
    [Fax]                   VARCHAR (50)  NULL,
    [Phone]                 VARCHAR (50)  NULL,
    [Phone2]                VARCHAR (50)  NULL,
    [Title]                 VARCHAR (50)  NULL,
    [Email]                 VARCHAR (50)  NULL,
    [Comment]               TEXT          NULL,
    [Comment2]              TEXT          NULL,
    [IsClient]              BIT           NULL,
    [Status]                VARCHAR (20)  NULL,
    [DeptID]                VARCHAR (8)   NULL,
    [RolodexID]             INT           NULL,
    [Supervisor]            VARCHAR (20)  NULL,
    [CLNO]                  INT           NULL,
    [EmplContactMethod]     INT           NULL,
    [EmplReleaseRequired]   BIT           NULL,
    [PreferredInvestigator] VARCHAR (20)  NULL,
    [WorkNumberID]          INT           NULL,
    [AliasList]             VARCHAR (MAX) NULL,
    [ExternalReferenceIDs]  VARCHAR (500) NULL,
    CONSTRAINT [PK_RolodexReview] PRIMARY KEY CLUSTERED ([ReviewID] ASC)
) TEXTIMAGE_ON [PRIMARY];

