CREATE TABLE [dbo].[Stg_PreEmpl_AutomationResults] (
    [BatchId]                VARCHAR (32)  NOT NULL,
    [RecordId]               INT           NOT NULL,
    [ProvidedFirst]          VARCHAR (100) NULL,
    [ProvidedLast]           VARCHAR (100) NULL,
    [ProvidedLicenseNumber]  VARCHAR (100) NULL,
    [ElapsedTime]            VARCHAR (20)  NULL,
    [LicenseId]              INT           NOT NULL,
    [ProvidedExpirationDate] DATETIME      NULL,
    [DisciplinaryAction]     VARCHAR (100) NULL,
    [LicenseNumber]          VARCHAR (100) NULL,
    [LicenseType]            VARCHAR (100) NULL,
    [ExpirationDate]         DATETIME      NULL,
    [ExpirationDateStr]      VARCHAR (30)  NULL,
    [IssueDate]              VARCHAR (20)  NULL,
    [IssueDateConverted]     VARCHAR (20)  NULL,
    [First]                  VARCHAR (100) NULL,
    [Last]                   VARCHAR (100) NULL,
    [Middle]                 VARCHAR (100) NULL,
    [LicenseStatus]          VARCHAR (200) NULL,
    [Name]                   VARCHAR (200) NULL,
    [NotFound]               VARCHAR (50)  NULL,
    [MultiStateStatus]       VARCHAR (50)  NULL,
    [ErrorMessage]           VARCHAR (250) NULL,
    [Suffix]                 VARCHAR (50)  NULL,
    [RuleResult]             VARCHAR (100) NULL,
    [PrevSectStat]           CHAR (1)      NULL,
    [NextSectStat]           CHAR (1)      NULL,
    [PrevSectSubStatusID]    INT           NULL,
    [NextSectSubStatusID]    INT           NULL,
    [NextPubNotes]           VARCHAR (MAX) NULL,
    [NextPrivNotes]          VARCHAR (MAX) NULL,
    [NextLicenseTypeId]      INT           NULL,
    [NextLicenseAuthorityId] INT           NULL,
    [AgentDateFormat]        VARCHAR (250) NULL
);

