CREATE TABLE [dbo].[Talx_Mar2022_Invoice] (
    [Invoice_Number]            INT            NULL,
    [Cust_No]                   INT            NULL,
    [Product_Description]       NVARCHAR (100) NULL,
    [Transaction_Description]   NVARCHAR (100) NULL,
    [Date]                      DATETIME       NULL,
    [Time]                      TIME (7)       NULL,
    [Unit_Price]                NVARCHAR (50)  NULL,
    [Quantity]                  NVARCHAR (50)  NULL,
    [Extended_Amt]              NVARCHAR (50)  NULL,
    [State]                     NVARCHAR (1)   NULL,
    [Reference_ExtOrd_No]       FLOAT (53)     NULL,
    [Source]                    NVARCHAR (50)  NULL,
    [Tracking]                  NVARCHAR (50)  NULL,
    [UserId]                    NVARCHAR (50)  NULL,
    [Cost_Center]               NVARCHAR (1)   NULL,
    [Branch_Division]           NVARCHAR (50)  NULL,
    [Branch_Name_Division_Name] NVARCHAR (1)   NULL,
    [Lender_Id]                 INT            NULL,
    [Verifier_Id]               INT            NULL,
    [Verifier_Name]             NVARCHAR (50)  NULL,
    [Company_Code]              INT            NULL,
    [Borrower]                  NVARCHAR (50)  NULL,
    [Request_Id]                NVARCHAR (1)   NULL,
    [SSN_EIN]                   NVARCHAR (50)  NULL,
    [CONSUMER_FIRSTNAME]        NVARCHAR (50)  NULL
);

