CREATE TABLE [dbo].[Talx_Apr2022_Invoice] (
    [Invoice_Number]            INT            NULL,
    [Cust]                      INT            NULL,
    [Product_Description]       NVARCHAR (100) NULL,
    [Transaction_Description]   NVARCHAR (100) NULL,
    [Date]                      DATE           NULL,
    [Time]                      TIME (7)       NULL,
    [Unit_Price]                FLOAT (53)     NULL,
    [Quantity]                  TINYINT        NULL,
    [Extended_amt]              FLOAT (53)     NULL,
    [State]                     NVARCHAR (2)   NULL,
    [AuthorizedUser]            NVARCHAR (1)   NULL,
    [Reference_ExtOrd_no]       FLOAT (53)     NULL,
    [Source]                    NVARCHAR (50)  NULL,
    [Tracking]                  NVARCHAR (50)  NULL,
    [UserID]                    NVARCHAR (50)  NULL,
    [Cost_Center]               NVARCHAR (1)   NULL,
    [Cost_Center_Name]          NVARCHAR (1)   NULL,
    [Branch_Division]           NVARCHAR (50)  NULL,
    [Branch_Name_Division_Name] NVARCHAR (1)   NULL,
    [Lenderid]                  INT            NULL,
    [Verifier_ID]               INT            NULL,
    [Verifier_Name]             NVARCHAR (50)  NULL,
    [Company_Code]              INT            NULL,
    [Borrower]                  NVARCHAR (50)  NULL,
    [Loan_Number_Manual]        NVARCHAR (1)   NULL,
    [Request_ID]                NVARCHAR (1)   NULL,
    [Loan_Number_Instant]       NVARCHAR (1)   NULL,
    [Cost_Center_Spectrum]      NVARCHAR (1)   NULL,
    [SSN_EIN]                   NVARCHAR (50)  NULL,
    [Consumer_Firstname]        NVARCHAR (50)  NULL,
    [Borrower_Status]           NVARCHAR (50)  NULL,
    [Master_Reference_Number]   NVARCHAR (50)  NULL,
    [End_User]                  NVARCHAR (100) NULL,
    [End_User_Name]             NVARCHAR (1)   NULL
);

