CREATE TABLE [dbo].[talx_July2022_Invoice] (
    [Invoice_Number]            FLOAT (53)     NULL,
    [Cust #]                    FLOAT (53)     NULL,
    [Product Description]       NVARCHAR (255) NULL,
    [Transaction Description]   NVARCHAR (255) NULL,
    [Date]                      DATETIME       NULL,
    [Time]                      DATETIME       NULL,
    [Unit_Price]                FLOAT (53)     NULL,
    [Quantity]                  FLOAT (53)     NULL,
    [Extended_amt]              FLOAT (53)     NULL,
    [State]                     NVARCHAR (255) NULL,
    [AuthorizedUser#]           NVARCHAR (255) NULL,
    [Reference_ExtOrd_No]       FLOAT (53)     NULL,
    [Source]                    NVARCHAR (255) NULL,
    [Tracking]                  NVARCHAR (255) NULL,
    [UserID]                    NVARCHAR (255) NULL,
    [Cost Center]               NVARCHAR (255) NULL,
    [Cost Center Name]          NVARCHAR (255) NULL,
    [Branch/Division]           NVARCHAR (255) NULL,
    [Branch Name/Division Name] NVARCHAR (255) NULL,
    [Lenderid]                  NVARCHAR (255) NULL,
    [Verifier_ID]               FLOAT (53)     NULL,
    [Verifier_Name]             NVARCHAR (255) NULL,
    [Company_Code]              FLOAT (53)     NULL,
    [Borrower]                  NVARCHAR (255) NULL,
    [Loan Number Manual]        NVARCHAR (255) NULL,
    [Request ID]                NVARCHAR (255) NULL,
    [Loan Number Instant]       NVARCHAR (255) NULL,
    [Cost Center Spectrum]      NVARCHAR (255) NULL,
    [SSN_EIN]                   NVARCHAR (255) NULL,
    [Consumer_Firstname]        NVARCHAR (255) NULL,
    [Borrower Status]           NVARCHAR (255) NULL,
    [Master Reference Number]   NVARCHAR (255) NULL,
    [End User]                  NVARCHAR (255) NULL,
    [End User Name]             NVARCHAR (255) NULL
);

