CREATE TABLE [dbo].[VA_Switch_From_WSS_To_Innovative] (
    [vendorid]                  NVARCHAR (255) NULL,
    [vendorname]                NVARCHAR (255) NULL,
    [r_delivery]                NVARCHAR (255) NULL,
    [Researcher_county]         NVARCHAR (255) NULL,
    [R_State_Province]          NVARCHAR (255) NULL,
    [Researcher_combo]          MONEY          NULL,
    [Researcher_other]          MONEY          NULL,
    [Researcher_CourtFees]      MONEY          NULL,
    [Researcher_aliases_count]  FLOAT (53)     NULL,
    [Preferred Vendor]          NVARCHAR (255) NULL,
    [County ID]                 NVARCHAR (255) NULL,
    [EmptyRow]                  NVARCHAR (255) NULL,
    [vendorid1]                 NVARCHAR (255) NULL,
    [vendorname1]               NVARCHAR (255) NULL,
    [r_delivery1]               NVARCHAR (255) NULL,
    [County]                    NVARCHAR (255) NULL,
    [State]                     NVARCHAR (255) NULL,
    [Researcher_combo1]         MONEY          NULL,
    [Researcher_other1]         MONEY          NULL,
    [Researcher_CourtFees1]     MONEY          NULL,
    [Researcher_aliases_count1] FLOAT (53)     NULL,
    [Preferred Vendor1]         NVARCHAR (255) NULL,
    [County ID1]                NVARCHAR (255) NULL
);

