CREATE PROCEDURE InsertEmpl
  @EmplID int,
  @Apno int,
  @Employer varchar(30),
  @Location varchar(30),
  @SectStat char(1),
  @Worksheet bit,
  @Phone varchar(20),
  @Supervisor varchar(25),
  @Dept varchar(30),
  @RFL varchar(30),
  @DNC bit,
  @SpecialQ bit,
  @Ver_Salary bit,
  @From_A varchar(8),
  @To_A varchar(8),
  @Position_A varchar(25),
  @Salary_A varchar(15),
  @From_V varchar(8),
  @To_V varchar(8),
  @Position_V varchar(25),
  @Salary_V varchar(15),
  @Emp_Type char(1),
  @Rel_Cond char(1),
  @Rehire varchar(1),
  @Ver_By varchar(25),
  @Title varchar(25),
  @Priv_Notes text,
  @Pub_Notes text
as
  set nocount on
  insert into Empl
    (EmplID, Apno, Employer, Location,
      SectStat, Worksheet, Phone, Supervisor,
      Dept, RFL, DNC, SpecialQ, Ver_Salary,
      From_A, To_A, Position_A,
      Salary_A, From_V, To_V,
      Position_V, Salary_V, Emp_Type,
      Rel_Cond, Rehire, Ver_By,
      Title, Priv_Notes, Pub_Notes)
  values
    (@EmplID, @Apno, @Employer, @Location,
      @SectStat, @Worksheet, @Phone, @Supervisor,
      @Dept, @RFL, @DNC, @SpecialQ, @Ver_Salary,
      @From_A, @To_A, @Position_A,
      @Salary_A, @From_V, @To_V,
      @Position_V, @Salary_V, @Emp_Type,
      @Rel_Cond, @Rehire, @Ver_By,
      @Title, @Priv_Notes, @Pub_Notes)
