CREATE TABLE [STG].[ApplicantEducation_CT] (
    [CommitDateTime]       DATETIME      NULL,
    [Operation]            VARCHAR (3)   NULL,
    [__$start_lsn]         BINARY (10)   NULL,
    [__$end_lsn]           BINARY (10)   NULL,
    [__$seqval]            BINARY (10)   NULL,
    [__$operation]         INT           NULL,
    [__$update_mask]       BINARY (128)  NULL,
    [ApplicantId]          INT           NULL,
    [CreateDate]           DATETIME      NULL,
    [CreateBy]             INT           NULL,
    [ModifyDate]           DATETIME      NULL,
    [ModifyBy]             INT           NULL,
    [ApplicantEducationId] INT           NULL,
    [SchoolName]           VARCHAR (100) NULL,
    [CampusName]           VARCHAR (50)  NULL,
    [NameOnDegree]         VARCHAR (100) NULL,
    [DegreeName]           VARCHAR (50)  NULL,
    [City]                 VARCHAR (50)  NULL,
    [State]                VARCHAR (20)  NULL,
    [Country]              VARCHAR (50)  NULL,
    [DAEducationLevelId]   INT           NULL,
    [Major]                VARCHAR (50)  NULL,
    [AttendedFrom]         DATETIME      NULL,
    [AttendedTo]           DATETIME      NULL,
    [IsGraduated]          BIT           NULL,
    [GraduationYear]       INT           NULL,
    [ApplicantNumber]      INT           NULL
);

