CREATE TABLE [STG].[ApplicantEmployment_CT] (
    [CommitDateTime]        DATETIME      NULL,
    [Operation]             VARCHAR (3)   NULL,
    [__$start_lsn]          BINARY (10)   NULL,
    [__$end_lsn]            BINARY (10)   NULL,
    [__$seqval]             BINARY (10)   NULL,
    [__$operation]          INT           NULL,
    [__$update_mask]        BINARY (128)  NULL,
    [ApplicantId]           INT           NULL,
    [CreateDate]            DATETIME      NULL,
    [CreateBy]              INT           NULL,
    [ModifyDate]            DATETIME      NULL,
    [ModifyBy]              INT           NULL,
    [City]                  VARCHAR (50)  NULL,
    [State]                 VARCHAR (20)  NULL,
    [Country]               VARCHAR (50)  NULL,
    [ApplicantEmploymentId] INT           NULL,
    [EmployerName]          VARCHAR (100) NULL,
    [ReasonForLeaving]      VARCHAR (100) NULL,
    [IsPresentEmployer]     BIT           NULL,
    [IsOKToContact]         BIT           NULL,
    [Address]               VARCHAR (100) NULL,
    [Zip]                   VARCHAR (10)  NULL,
    [EmploymentFrom]        DATE          NULL,
    [EmploymentTo]          DATE          NULL,
    [StartSalary]           INT           NULL,
    [EndSalary]             INT           NULL,
    [StartDesignation]      VARCHAR (70)  NULL,
    [EndDesignation]        VARCHAR (70)  NULL,
    [SupervisorName]        VARCHAR (150) NULL,
    [SupervisorPhone]       VARCHAR (20)  NULL,
    [SupervisorEmail]       VARCHAR (250) NULL,
    [ApplicantNumber]       INT           NULL
);

